"use client";
/**
 * The three dialogs a revision row opens: roll this environment back to it,
 * promote it to another environment, and read its manifest.
 *
 * Roll back and promote are the same action — deploy a chosen revision to a
 * chosen environment — so they share a plan-first confirm and differ only in
 * the verb and in what they warn about.
 */
import type { Environment, Revision } from "@/lib/domain/types";
import { Button } from "@/components/ui/button";
import { CodeBlock } from "@/components/ui/code-block";
import { Dialog } from "@/components/ui/dialog";
import { Select } from "@/components/ui/select";
import type { RevisionMeta } from "@/components/screens/project-data";
import { ActionConfirm } from "@/components/screens/shared";
import { LeavingNote } from "./compare";

/** Roll one environment back to a revision it is not already running. */
export function RollbackDialog({
  env,
  projectId,
  target,
  liveIn,
  onClose,
  onDone,
}: {
  env: Environment;
  projectId: string;
  /** the revision to roll back to; `undefined` keeps the dialog closed */
  target: RevisionMeta | undefined;
  liveIn: Map<string, Environment[]>;
  onClose: () => void;
  onDone: () => void;
}) {
  return (
    <ActionConfirm
      open={target !== undefined}
      onClose={onClose}
      actionId="deploy.rollback"
      input={{ environmentId: env.id, toRevisionId: target?.id }}
      scope={{ projectId, environmentId: env.id }}
      title={`Roll ${env.name} back to r${target?.number ?? ""}`}
      description="Restores this system definition through a new deployment, with its own steps and logs. History is preserved. Deleted or changed application data is not recovered."
      confirmLabel="Roll back"
      danger
      typeToConfirm={env.class === "production" ? env.name : undefined}
      onDone={onDone}
    >
      <LeavingNote env={env} liveIn={liveIn} />
    </ActionConfirm>
  );
}

export interface PromoteTarget {
  revision: RevisionMeta;
  environmentId: string;
}

/** Deploy a revision to a second environment — the working copy is untouched. */
export function PromoteDialog({
  projectId,
  environments,
  target,
  onChange,
  onClose,
  onDone,
}: {
  projectId: string;
  environments: Environment[];
  target: PromoteTarget;
  onChange: (next: PromoteTarget) => void;
  onClose: () => void;
  onDone: () => void;
}) {
  return (
    <ActionConfirm
      open
      onClose={onClose}
      // Same action, same plan-first path: the engine already deploys any
      // revision to any environment. Only the verb differs.
      actionId="deploy.rollback"
      input={{ environmentId: target.environmentId, toRevisionId: target.revision.id }}
      scope={{ projectId, environmentId: target.environmentId }}
      title={`Promote r${target.revision.number} to ${
        environments.find((e) => e.id === target.environmentId)?.name ?? "another environment"
      }`}
      description="Deploys this exact revision to another environment — the working copy is not touched."
      danger={environments.find((e) => e.id === target.environmentId)?.class === "production"}
      confirmLabel="Promote"
      typeToConfirm={
        environments.find((e) => e.id === target.environmentId)?.class === "production"
          ? environments.find((e) => e.id === target.environmentId)?.name
          : undefined
      }
      onDone={onDone}
    >
      <div className="space-y-2">
        <label className="block space-y-1.5">
          <span className="text-[12px] tracking-[0.02em] text-ink-mute uppercase">
            Deploy r{target.revision.number} to
          </span>
          <Select
            value={target.environmentId}
            onChange={(e) => onChange({ ...target, environmentId: e.target.value })}
            options={environments.map((e) => ({
              value: e.id,
              label:
                e.deployedRevisionId === target.revision.id
                  ? `${e.name} — already runs r${target.revision.number}`
                  : e.name,
              disabled: e.deployedRevisionId === target.revision.id,
            }))}
          />
        </label>
        <p className="text-[12px] text-ink-faint">
          Promote and roll back are one operation: deploy a chosen revision to an environment.
          The preview below is generated by that action and still words it as a rollback.
        </p>
      </div>
    </ActionConfirm>
  );
}

/** The exact manifest a revision deployed, read-only. */
export function ViewDialog({
  target,
  onClose,
}: {
  /** the fetched revision and its row metadata; `undefined` keeps it closed */
  target: { meta: RevisionMeta; revision: Revision } | undefined;
  onClose: () => void;
}) {
  return (
    <Dialog
      open={target !== undefined}
      onClose={onClose}
      title={`r${target?.meta.number ?? ""} — ${target?.meta.message ?? ""}`}
      description="The exact manifest this revision deployed. Revisions are immutable; this is read-only."
      width={720}
      footer={
        <Button variant="quiet" onClick={onClose}>
          Close
        </Button>
      }
    >
      {target?.revision && (
        <CodeBlock
          code={JSON.stringify(target.revision.manifest, null, 2)}
          title={`r${target.meta.number}.json`}
          lineNumbers
          maxHeight={460}
        />
      )}
    </Dialog>
  );
}
