"use client";
import type { ReactNode } from "react";
import type { ProviderRow } from "./landing";
import styles from "./narrative-body.module.css";

const NODES=["App","Jobs","Storage","Database"];
function Map({proposed=false}:{proposed?:boolean}){return <div className={styles.map} aria-label={proposed?"Proposed system":"Current system"}>{NODES.map((n,i)=><span key={n} className={styles.node} data-proposed={proposed&&i===1||undefined}>{n}</span>)}</div>}
function Status({children,tone}:{children:ReactNode;tone:string}){return <span className={styles.status} data-status={tone}><i />{children}</span>}

export function NarrativeBody({providers}:{providers:ProviderRow[]}){
 const aws=providers.find(p=>p.id.toLowerCase().includes("aws"));
 const local=providers.find(p=>p.id.toLowerCase().includes("local"));
 return <>
  <section className={styles.bridge}><p className={styles.kicker}>Built for teams moving faster than their infrastructure</p><h1>Your app is moving fast.<br/><em>Your infrastructure should still make sense.</em></h1><p className={styles.lede}>Zenith gives small software teams one clear place to understand the system behind their app, preview the next change, and decide what is allowed to run.</p></section>
  <section className={styles.split}><div><p className={styles.kicker}>One place to understand what you are building</p><h2>Your whole app,<br/><em>in one picture.</em></h2><p className={styles.body}>Services, data and connections stay in one shared view. The picture stays connected to the system it describes instead of becoming another diagram to maintain.</p></div><div className={styles.darkCard}><Map/><footer><b>One shared picture</b><span>System stays in sync</span></footer></div></section>
  <section className={styles.three}>{[["See it.","Understand the whole system without assembling the story from disconnected tools."],["Preview it.","Know what will change, what it affects, and the estimated impact before anything runs."],["Decide.","You choose what crosses the line from a proposal into a real change."]].map((x,i)=><article key={x[0]}><b>0{i+1}</b><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</section>
  <section className={styles.section+" "+styles.changeStory}><header><p className={styles.kicker}>The important moment is before execution</p><h2>Know what changes<br/><em>before it changes.</em></h2></header><div className={styles.change}><div className={styles.state+" "+styles.current}><small>NOW</small><Map/></div><span className={styles.arrow}>→</span><div className={styles.state+" "+styles.proposed}><small>PROPOSED</small><Map proposed/></div><aside><small>ESTIMATED IMPACT</small><strong>+ background jobs</strong><p>Affected connections become visible before approval.</p><Status tone="available">Low risk</Status></aside></div><ol className={styles.loop}>{["Intent","Plan","Impact","Approval","Change"].map(x=><li key={x} data-gate={x==="Approval"||undefined}>{x}</li>)}</ol></section>
  <section className={styles.section}><header><p className={styles.kicker}>For teams that need a platform, not a platform team</p><h2>Built for lean teams<br/><em>shipping real software.</em></h2></header><div className={styles.people}><article><span>Solo founder</span><h3>Keep shipping without losing the plot.</h3><p>Your product can grow in a weekend. Zenith keeps what runs underneath it understandable.</p></article><article><span>Small team</span><h3>Give everyone the same picture.</h3><p>See what exists and what changes next without stitching together ten operational surfaces.</p></article><article><span>AI-native team</span><h3>Let agents help without losing the boundary.</h3><p>Automation can move faster while the decision path remains visible and controlled.</p></article></div></section>
  <section className={styles.agent+" zenith-ink"}><div><p className={styles.kicker}>Humans and agents, one controlled path</p><h2>Agents don’t get<br/><em>a side door.</em></h2><p className={styles.body}>Whether a change starts with you or an agent, it enters the same visible plan, review and approval path.</p></div><div className={styles.flow}><div className={styles.origins}><span>You</span><span>Agent</span></div><b>→</b>{["Plan","Review","Approval","Run"].map(x=><span key={x} className={x==="Approval"?styles.gate:""}>{x}{x==="Approval"&&<i/>}</span>)}</div></section>
  <section className={styles.section+" "+styles.architecture}><header><p className={styles.kicker}>Built differently on purpose</p><h2>One system<br/><em>underneath everything.</em></h2><p className={styles.body}>These are not unrelated features. They are consequences of keeping the picture, plan, action path and portable output connected.</p></header><div className={styles.core} aria-hidden="true"><span>ONE SYSTEM</span><i/><i/><i/><i/></div><div className={styles.moat}>{[["One shared picture","The system view comes from the same underlying representation used to operate it."],["Plan before change","Requests become understandable plans with impact before execution."],["Same rules","People and agents use the same controlled action boundary."],["Your system stays yours","Portable definitions, Terraform and operating information can leave with you."]].map(x=><article key={x[0]}><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></section>
  <section className={styles.truth}><div><p className={styles.kicker}>Honesty is part of the product</p><h2>Know what is<br/><em>real today.</em></h2><p className={styles.body}>Zenith distinguishes what is available, simulated, in preview and still planned. No pretend green checks.</p></div><div className={styles.truthList}><article><Status tone="simulated">Simulated</Status><h3>Sandbox</h3><p>Safe practice. No cloud resources are created.</p></article><article><Status tone="available">Available locally</Status><h3>{local?.displayName??"LocalStack"}</h3><p>Supported local operations use real local services.</p></article><article><Status tone="preview">Preview</Status><h3>{aws?.displayName??"AWS"}</h3><p>Prepare plans and export Terraform; no in-app AWS deployment yet.</p></article><article><Status tone="planned">Planned</Status><h3>More providers</h3><p>Roadmap capability is labeled as roadmap, not available today.</p></article></div></section>
 </>;
}