"use client";
/**
 * An incident investigation: the request path with each hop's status, the
 * hypotheses ranked by the confidence their rule computed, the evidence behind
 * each one, and the fixes that could be proposed.
 *
 * Reading guide, printed on the surface itself: "Evidence is observed data;
 * hypotheses are rule-based." Confidence is a number from the rules (which checks
 * passed and failed), not a model's guess and not a probability, and the view says
 * so. Nothing here re-ranks, hides contradicting evidence, or invents a cause: a
 * hypothesis that cites evidence missing from the investigation says so, and an
 * investigation with no hypotheses says that is not the same as "nothing is wrong".
 * Remediation risk and "needs approval" come from the data (a policy dry-run), and
 * the propose button only exists when the host supplied a handler.
 */
import { Fragment, useId } from "react";
import { ArrowRight, Search } from "lucide-react";
import type { Evidence, Hop, Hypothesis, Investigation, RemediationOption } from "@/lib/incidents/types";
import { Button } from "@/components/ui/button";
import { Callout } from "@/components/ui/callout";
import { Card } from "@/components/ui/card";
import { Chip, type ChipTone } from "@/components/ui/chip";
import { EmptyState } from "@/components/ui/empty-state";
import { Meter } from "@/components/ui/meter";
import { TimeAgo } from "@/components/ui/time-ago";
import { SimulatedChip } from "@/components/screens/badges";
import { SurfaceGate, type AsyncSurfaceProps } from "./async-gate";
import { Disclosure, RiskLabel } from "./badges";
import { HOP_LABEL, HYPOTHESIS_CATEGORY_LABEL } from "./labels";
import {
  INVESTIGATION_NOTE,
  resolveEvidence,
  sortHypotheses,
  tallyEvidence,
} from "./investigation-model";
import { humanizeToken, plural, toPercent } from "./text";

export interface InvestigationViewProps extends AsyncSurfaceProps {
  investigation?: Investigation;
  /** When given, each remediation gets a "Propose this fix" button. Omit it and no button is drawn. */
  onProposeRemediation?: (option: RemediationOption, hypothesis: Hypothesis) => void;
  /** Why proposing is unavailable right now (for example the viewer's role); disables every propose button with this sentence. */
  proposeDisabledReason?: string;
  /** capability name to human title, from the catalog; unknown names fall back to a readable form */
  capabilityTitles?: Readonly<Record<string, string>>;
  title?: string;
}

const HOP_STATUS: Record<Investigation["path"][number]["status"], { label: string; tone: ChipTone; title: string }> = {
  healthy: { label: "Healthy", tone: "ok", title: "The checks at this hop passed." },
  failing: { label: "Failing", tone: "err", title: "A check at this hop failed." },
  unknown: { label: "Unknown", tone: "neutral", title: "Zenith could not tell whether this hop is working." },
};

const OUTCOME: Record<Evidence["outcome"], { label: string; tone: ChipTone }> = {
  pass: { label: "Passed", tone: "ok" },
  fail: { label: "Failed", tone: "err" },
  unknown: { label: "Inconclusive", tone: "neutral" },
};

function EvidenceItem({ evidence }: { evidence: Evidence }) {
  const o = OUTCOME[evidence.outcome];
  return (
    <li className="space-y-1 border-b border-line py-2 last:border-b-0">
      <div className="flex flex-wrap items-center gap-x-2 gap-y-1">
        <Chip tone={o.tone}>{o.label}</Chip>
        <span className="text-[12.5px] text-ink-mute">
          {HOP_LABEL[evidence.hop as Hop] ?? humanizeToken(evidence.hop)}
          {evidence.address ? <span className="font-mono text-[12px]"> · {evidence.address}</span> : null}
        </span>
        {evidence.simulated && <SimulatedChip title="This evidence was generated by a simulation; nothing real was checked." />}
      </div>
      <p className="text-[13px] text-ink">{evidence.finding}</p>
      <p className="flex flex-wrap items-center gap-x-3 text-[12px] text-ink-faint">
        <span>
          Check <code className="font-mono">{evidence.check}</code>
        </span>
        <TimeAgo iso={evidence.observedAt} prefix="observed" />
      </p>
    </li>
  );
}

function EvidenceList({ investigation, ids }: { investigation: Investigation; ids: readonly string[] }) {
  return (
    <ul>
      {resolveEvidence(investigation, ids).map((r) =>
        r.evidence ? (
          <EvidenceItem key={r.id} evidence={r.evidence} />
        ) : (
          <li key={r.id} className="border-b border-line py-2 text-[12.5px] text-warn last:border-b-0">
            This hypothesis cites evidence <code className="font-mono">{r.id}</code>, but it is not included in this investigation.
          </li>
        )
      )}
    </ul>
  );
}

function HypothesisCard({
  hypothesis,
  investigation,
  rank,
  onPropose,
  proposeDisabledReason,
  capabilityTitles,
}: {
  hypothesis: Hypothesis;
  investigation: Investigation;
  rank: number;
  onPropose?: InvestigationViewProps["onProposeRemediation"];
  proposeDisabledReason?: string;
  capabilityTitles?: InvestigationViewProps["capabilityTitles"];
}) {
  const uid = useId();
  const pct = toPercent(hypothesis.confidence);
  const support = hypothesis.supportingEvidence;
  const contra = hypothesis.contradictingEvidence;
  return (
    <article className="space-y-3 rounded-card border border-line bg-bg2 p-4" data-rank={rank}>
      <header className="space-y-1.5">
        <div className="flex flex-wrap items-center gap-2">
          <h5 className="text-[14px] font-medium text-ink">{hypothesis.title}</h5>
          <Chip>{HYPOTHESIS_CATEGORY_LABEL[hypothesis.category]}</Chip>
          {rank === 0 && pct !== undefined && <Chip tone="info">Highest confidence</Chip>}
        </div>
        {pct !== undefined ? (
          <div className="max-w-sm">
            <Meter
              value={pct}
              tone="info"
              label="Confidence"
              hint={`${pct}%`}
            />
          </div>
        ) : (
          <p className="text-[12.5px] text-ink-mute">Confidence unavailable for this hypothesis.</p>
        )}
      </header>

      {support.length === 0 && contra.length === 0 ? (
        <p className="text-[12.5px] text-ink-mute">No evidence was recorded for this hypothesis.</p>
      ) : (
        <div className="space-y-2">
          {support.length > 0 && (
            <Disclosure summary={`Supporting evidence (${support.length})`}>
              <EvidenceList investigation={investigation} ids={support} />
            </Disclosure>
          )}
          {contra.length > 0 && (
            <Disclosure summary={`Contradicting evidence (${contra.length})`}>
              <EvidenceList investigation={investigation} ids={contra} />
            </Disclosure>
          )}
        </div>
      )}

      {hypothesis.remediations.length > 0 ? (
        <div className="space-y-2">
          <h6 className="text-[12.5px] font-medium text-ink-mute">Possible fixes</h6>
          <ul className="space-y-2">
            {hypothesis.remediations.map((r) => (
              <li key={r.id} className="space-y-1.5 rounded-ctl border border-line bg-bg1 px-3 py-2.5">
                <div className="flex flex-wrap items-center gap-2">
                  <span className="text-[13px] font-medium text-ink">{r.title}</span>
                  <Chip title="The action this fix would request">
                    {capabilityTitles?.[r.request.capability] ?? humanizeToken(r.request.capability)}
                  </Chip>
                  <RiskLabel level={r.risk} />
                  <Chip tone={r.approvalRequired ? "warn" : "neutral"}>
                    {r.approvalRequired ? "Needs approval" : "Runs without approval"}
                  </Chip>
                </div>
                <p className="text-[12.5px] text-ink-mute">
                  <span className="text-ink-faint">Expected effect: </span>
                  {r.expectedEffect}
                </p>
                <p className="text-[12.5px] text-ink-mute">
                  <span className="text-ink-faint">Reversibility: </span>
                  {r.reversibility}
                </p>
                {onPropose && (
                  <div className="flex flex-wrap items-center gap-2 pt-0.5">
                    <Button
                      size="sm"
                      variant="quiet"
                      disabled={Boolean(proposeDisabledReason)}
                      disabledReason={proposeDisabledReason}
                      aria-describedby={proposeDisabledReason ? `${uid}-${r.id}-why` : undefined}
                      aria-label={`Propose this fix: ${r.title}`}
                      onClick={() => onPropose(r, hypothesis)}
                    >
                      Propose this fix
                    </Button>
                    {proposeDisabledReason ? (
                      <span id={`${uid}-${r.id}-why`} className="text-[12px] text-ink-mute">
                        {proposeDisabledReason}
                      </span>
                    ) : (
                      <span className="text-[12px] text-ink-faint">
                        This creates a proposal. Nothing runs until policy and any required approval allow it.
                      </span>
                    )}
                  </div>
                )}
              </li>
            ))}
          </ul>
        </div>
      ) : (
        <p className="text-[12.5px] text-ink-mute">No fix was suggested for this hypothesis.</p>
      )}
    </article>
  );
}

export function InvestigationView({
  investigation,
  onProposeRemediation,
  proposeDisabledReason,
  capabilityTitles,
  title = "Investigation",
  loading,
  error,
  onRetry,
}: InvestigationViewProps) {
  const hypotheses = investigation ? sortHypotheses(investigation.hypotheses) : [];
  const t = investigation ? tallyEvidence(investigation.evidence) : { pass: 0, fail: 0, unknown: 0 };

  return (
    <Card
      title={title}
      subtitle={INVESTIGATION_NOTE}
      actions={
        investigation?.simulated ? (
          <SimulatedChip title="This investigation ran against a simulation; no real infrastructure was checked." />
        ) : undefined
      }
    >
      <SurfaceGate loading={loading} error={error} onRetry={onRetry} what="the investigation" rows={5}>
        {!investigation ? (
          <EmptyState
            icon={<Search className="h-5 w-5" aria-hidden="true" />}
            title="No investigation yet"
            body="When something looks wrong, an investigation checks each hop of the request path and lists what it found."
          />
        ) : (
          <div className="space-y-6">
            <p className="text-[12.5px] text-ink-mute">
              Confidence comes from which checks passed and failed, by fixed rules. It is a ranking, not a probability, and a model cannot add evidence.
            </p>

            <section aria-label="Request path" className="space-y-2">
              <h4 className="text-[13px] font-medium text-ink-mute">Request path</h4>
              {investigation.path.length === 0 ? (
                <p className="text-[13px] text-ink-mute">No hops were traversed, so nothing about the request path is known.</p>
              ) : (
                <ol className="flex flex-wrap items-stretch gap-x-1 gap-y-2">
                  {investigation.path.map((hop, i) => {
                    const s = HOP_STATUS[hop.status];
                    return (
                      <Fragment key={`${hop.hop}-${hop.address ?? i}-${i}`}>
                        {i > 0 && (
                          <li aria-hidden="true" className="flex items-center text-ink-faint">
                            <ArrowRight className="h-3.5 w-3.5" />
                          </li>
                        )}
                        <li data-hop-status={hop.status} className="min-w-[110px] space-y-1 rounded-ctl border border-line bg-bg2 px-3 py-2">
                          <div className="text-[13px] font-medium text-ink">{HOP_LABEL[hop.hop]}</div>
                          {hop.address && <div className="break-all font-mono text-[11.5px] text-ink-faint">{hop.address}</div>}
                          <Chip tone={s.tone} title={s.title}>
                            {s.label}
                          </Chip>
                        </li>
                      </Fragment>
                    );
                  })}
                </ol>
              )}
            </section>

            <section aria-label="Hypotheses" className="space-y-3">
              <h4 className="text-[13px] font-medium text-ink-mute">Hypotheses, highest confidence first</h4>
              {hypotheses.length === 0 ? (
                <Callout tone="info" title="No hypothesis matched the evidence">
                  That is not the same as nothing being wrong. The rules found {plural(t.pass, "check")} passing, {t.fail} failing and{" "}
                  {t.unknown} inconclusive.
                </Callout>
              ) : (
                hypotheses.map((h, i) => (
                  <HypothesisCard
                    key={h.id}
                    hypothesis={h}
                    investigation={investigation}
                    rank={i}
                    onPropose={onProposeRemediation}
                    proposeDisabledReason={proposeDisabledReason}
                    capabilityTitles={capabilityTitles}
                  />
                ))
              )}
            </section>

            {investigation.recentChanges.length > 0 && (
              <section aria-label="Recent changes" className="space-y-2">
                <h4 className="text-[13px] font-medium text-ink-mute">What changed recently</h4>
                <ul className="divide-y divide-line rounded-card border border-line">
                  {investigation.recentChanges.map((c, i) => (
                    <li key={`${c.at}-${i}`} className="flex flex-wrap items-baseline gap-x-3 gap-y-1 px-4 py-2.5 text-[13px]">
                      <TimeAgo iso={c.at} className="text-[12px] text-ink-faint" />
                      <Chip>{humanizeToken(c.kind)}</Chip>
                      <span className="min-w-0 flex-1 text-ink">{c.summary}</span>
                    </li>
                  ))}
                </ul>
              </section>
            )}

            <section aria-label="All checks" className="space-y-2">
              <Disclosure summary={`All checks that ran (${investigation.evidence.length})`}>
                {investigation.evidence.length === 0 ? (
                  <p className="text-[12.5px] text-ink-mute">No checks ran, so there is no evidence.</p>
                ) : (
                  <ul>
                    {investigation.evidence.map((e) => (
                      <EvidenceItem key={e.id} evidence={e} />
                    ))}
                  </ul>
                )}
              </Disclosure>
            </section>
          </div>
        )}
      </SurfaceGate>
    </Card>
  );
}
