/**
 * Badges for the three state levels of a resource. Each always prints its
 * label: a coloured dot on its own would leave "unknown" and "healthy" looking
 * alike to anyone who cannot see the colour, and "unknown" must never read as fine.
 */
import type { HealthState, Presence } from "@/lib/resources/types";
import { cx } from "@/lib/format";
import { Chip, type ChipTone } from "@/components/ui/chip";
import { TimeAgo } from "@/components/ui/time-ago";
import { SimulatedChip } from "@/components/screens/badges";
import { HEALTH_LABEL, PRESENCE_LABEL, PRESENCE_SENTENCE } from "./labels";

const PRESENCE_TONE: Record<Presence, ChipTone> = {
  present: "ok",
  missing: "err",
  inaccessible: "warn",
  unknown: "neutral",
};

/** `present` / `missing` / `not accessible` / `unknown`, or "Not observed yet" without an observation. */
export function PresenceBadge({ presence }: { presence: Presence | undefined }) {
  if (!presence) {
    return (
      <Chip tone="neutral" title="Nothing has read this resource at the provider yet.">
        Not observed yet
      </Chip>
    );
  }
  return (
    <Chip tone={PRESENCE_TONE[presence]} title={PRESENCE_SENTENCE[presence]}>
      {PRESENCE_LABEL[presence]}
    </Chip>
  );
}

const HEALTH_DOT: Record<HealthState, string> = {
  healthy: "bg-ok",
  degraded: "bg-warn",
  unhealthy: "bg-err",
  unknown: "bg-ink-faint",
};

const HEALTH_TEXT: Record<HealthState, string> = {
  healthy: "text-ink",
  degraded: "text-warn",
  unhealthy: "text-err",
  unknown: "text-ink-mute",
};

/** A decorative dot plus the health in words. `undefined` means runtime was never read. */
export function HealthBadge({ health }: { health: HealthState | undefined }) {
  if (!health) {
    return <span className="text-[12.5px] text-ink-mute">Runtime not read</span>;
  }
  return (
    <span className={cx("inline-flex items-center gap-1.5 text-[12.5px] font-medium", HEALTH_TEXT[health])}>
      <span aria-hidden="true" className={cx("h-2 w-2 rounded-full", HEALTH_DOT[health])} />
      {HEALTH_LABEL[health]}
    </span>
  );
}

/** "Read 4m ago" plus the simulated label when the source says so. */
export function ReadMeta({ at, simulated, prefix = "Read" }: { at: string; simulated: boolean; prefix?: string }) {
  return (
    <span className="inline-flex flex-wrap items-center gap-x-2 gap-y-1 text-[12px] text-ink-faint">
      <TimeAgo iso={at} prefix={prefix} />
      {simulated && <SimulatedChip title="This was generated by a simulation; no real infrastructure was read." />}
    </span>
  );
}
