/**
 * Which provider hosts which portable kind, and which catalog SKU prices which
 * cost role (ADR-0013, ADR-0003).
 *
 * `NATIVE_TYPES` uses the Level-2 vocabulary of `@/lib/resources/types`
 * (`aws:ecs_service`, `gcp:cloud_run_service`, ...). It is the placement
 * solver's capability table: a kind with no entry for a provider means the
 * provider cannot host it natively and the candidate is rejected with that
 * reason. Entries here are placement/cost knowledge; whether a driver for the
 * native type exists is decided elsewhere (drivers registry), so a candidate
 * can be cost-feasible on a provider whose driver is not written yet. The
 * solver reports that as a warning rather than pretending otherwise.
 *
 * `SKU_ROLES` maps a provider-agnostic cost role to that provider's catalog
 * SKU. Roles that a provider does not have (for example `lb_capacity_unit_hour`
 * on GCP, which meters processed GB instead) are simply absent.
 */
import type { PortableKind } from "@/lib/resources/types";

type NativeMap = Partial<Record<PortableKind, string>>;

const AWS: NativeMap = {
  network: "aws:vpc",
  subnet: "aws:subnet",
  firewall: "aws:security_group",
  load_balancer: "aws:alb",
  dns_zone: "aws:route53_zone",
  dns_record: "aws:route53_record",
  tls_certificate: "aws:acm_certificate",
  container_service: "aws:ecs_service",
  container_registry: "aws:ecr_repository",
  compute_instance: "aws:ec2_instance",
  function: "aws:lambda_function",
  static_site: "aws:s3_static_site",
  scheduled_job: "aws:ecs_scheduled_task",
  postgres: "aws:rds_postgres",
  mysql: "aws:rds_mysql",
  redis: "aws:elasticache_redis",
  object_store: "aws:s3_bucket",
  queue: "aws:sqs_queue",
  pubsub: "aws:sns_topic",
  secret: "aws:secretsmanager_secret",
  identity: "aws:iam_role",
  log_group: "aws:cloudwatch_log_group",
  kubernetes_cluster: "aws:eks_cluster",
  kubernetes_namespace: "k8s:Namespace",
  volume: "aws:ebs_volume",
  build_pipeline: "aws:codebuild_project",
};

const GCP: NativeMap = {
  network: "gcp:vpc_network",
  subnet: "gcp:subnetwork",
  firewall: "gcp:firewall_rule",
  load_balancer: "gcp:external_application_lb",
  dns_zone: "gcp:cloud_dns_zone",
  dns_record: "gcp:cloud_dns_record",
  tls_certificate: "gcp:managed_certificate",
  container_service: "gcp:cloud_run_service",
  container_registry: "gcp:artifact_registry_repository",
  compute_instance: "gcp:compute_instance",
  function: "gcp:cloud_function",
  static_site: "gcp:gcs_static_site",
  scheduled_job: "gcp:cloud_run_job",
  postgres: "gcp:cloud_sql_postgres",
  mysql: "gcp:cloud_sql_mysql",
  redis: "gcp:memorystore_redis",
  object_store: "gcp:gcs_bucket",
  queue: "gcp:cloud_tasks_queue",
  pubsub: "gcp:pubsub_topic",
  secret: "gcp:secret_manager_secret",
  identity: "gcp:service_account",
  log_group: "gcp:log_bucket",
  kubernetes_cluster: "gcp:gke_cluster",
  kubernetes_namespace: "k8s:Namespace",
  volume: "gcp:persistent_disk",
  build_pipeline: "gcp:cloud_build_trigger",
};

const AZURE: NativeMap = {
  network: "azure:virtual_network",
  subnet: "azure:subnet",
  firewall: "azure:network_security_group",
  load_balancer: "azure:application_gateway",
  dns_zone: "azure:dns_zone",
  dns_record: "azure:dns_record",
  tls_certificate: "azure:managed_certificate",
  container_service: "azure:container_app",
  container_registry: "azure:container_registry",
  compute_instance: "azure:linux_virtual_machine",
  function: "azure:function_app",
  static_site: "azure:static_web_app",
  scheduled_job: "azure:container_app_job",
  postgres: "azure:postgresql_flexible_server",
  mysql: "azure:mysql_flexible_server",
  redis: "azure:redis_cache",
  object_store: "azure:storage_container",
  queue: "azure:storage_queue",
  pubsub: "azure:service_bus_topic",
  secret: "azure:key_vault_secret",
  identity: "azure:managed_identity",
  log_group: "azure:log_analytics_workspace",
  kubernetes_cluster: "azure:aks_cluster",
  kubernetes_namespace: "k8s:Namespace",
  volume: "azure:managed_disk",
  build_pipeline: "azure:devops_build_pipeline",
};

const OCI: NativeMap = {
  network: "oci:vcn",
  subnet: "oci:subnet",
  firewall: "oci:network_security_group",
  load_balancer: "oci:flexible_load_balancer",
  dns_zone: "oci:dns_zone",
  dns_record: "oci:dns_rrset",
  tls_certificate: "oci:certificate",
  container_service: "oci:container_instance",
  container_registry: "oci:container_repository",
  compute_instance: "oci:compute_instance",
  function: "oci:functions_function",
  scheduled_job: "oci:container_instance",
  postgres: "oci:postgresql_db_system",
  mysql: "oci:mysql_db_system",
  redis: "oci:redis_cluster",
  object_store: "oci:object_storage_bucket",
  queue: "oci:queue",
  pubsub: "oci:notification_topic",
  secret: "oci:vault_secret",
  identity: "oci:dynamic_group",
  log_group: "oci:log_group",
  kubernetes_cluster: "oci:oke_cluster",
  kubernetes_namespace: "k8s:Namespace",
  volume: "oci:block_volume",
  build_pipeline: "oci:devops_build_pipeline",
};

const ZENITH: NativeMap = {
  network: "zenith:managed_network",
  subnet: "zenith:managed_network",
  firewall: "zenith:managed_network",
  load_balancer: "zenith:managed_edge",
  dns_zone: "zenith:managed_dns",
  dns_record: "zenith:managed_dns",
  tls_certificate: "zenith:managed_certificate",
  container_service: "zenith:managed_service",
  scheduled_job: "zenith:managed_job",
  postgres: "zenith:managed_postgres",
  redis: "zenith:managed_redis",
  object_store: "zenith:managed_bucket",
  queue: "zenith:managed_queue",
  secret: "zenith:managed_secret",
  identity: "zenith:managed_identity",
  log_group: "zenith:managed_logs",
};

export const NATIVE_TYPES: Readonly<Record<string, Readonly<NativeMap>>> = {
  aws: AWS,
  gcp: GCP,
  azure: AZURE,
  oci: OCI,
  zenith: ZENITH,
};

/** The native type realizing `kind` on `provider`, or undefined when the provider cannot host it. */
export function nativeTypeFor(provider: string, kind: PortableKind): string | undefined {
  return NATIVE_TYPES[provider]?.[kind];
}

/** Providers the catalog and solver know about, sorted. */
export function placementProviders(): string[] {
  return Object.keys(NATIVE_TYPES).sort();
}

/* --------------------------------- SKU roles ------------------------------ */

export const SKU_ROLES = [
  "container_vcpu_hour",
  "container_gb_hour",
  "vm_small_hour",
  "vm_medium_hour",
  "vm_large_hour",
  "pg_nano_hour",
  "pg_small_hour",
  "pg_standard_hour",
  "pg_performance_hour",
  "pg_ha_multiplier",
  "pg_ha_storage_multiplier",
  "pg_storage_gb_month",
  "pg_iops_month",
  "pg_backup_gb_month",
  "cache_nano_hour",
  "cache_small_hour",
  "cache_standard_hour",
  "cache_performance_hour",
  "cache_ha_multiplier",
  "object_storage_gb_month",
  "object_get_million",
  "object_put_million",
  "queue_requests_million",
  "lb_hour",
  "lb_capacity_unit_hour",
  "lb_processed_gb",
  "nat_hour",
  "nat_gb",
  "ipv4_hour",
  "egress_internet_gb",
  "egress_inter_region_gb",
  "block_gb_month",
  "block_iops_month",
  "block_snapshot_gb_month",
  "dns_zone_month",
  "dns_queries_million",
  "cert_month",
  "logs_ingest_gb",
] as const;
export type SkuRole = (typeof SKU_ROLES)[number];

type RoleMap = Partial<Record<SkuRole, string>>;

const AWS_SKUS: RoleMap = {
  container_vcpu_hour: "aws.fargate.vcpu_hour",
  container_gb_hour: "aws.fargate.gb_hour",
  vm_small_hour: "aws.ec2.small_hour",
  vm_medium_hour: "aws.ec2.medium_hour",
  vm_large_hour: "aws.ec2.large_hour",
  pg_nano_hour: "aws.rds_postgres.nano_hour",
  pg_small_hour: "aws.rds_postgres.small_hour",
  pg_standard_hour: "aws.rds_postgres.standard_hour",
  pg_performance_hour: "aws.rds_postgres.performance_hour",
  pg_ha_multiplier: "aws.rds_postgres.ha_multiplier",
  pg_ha_storage_multiplier: "aws.rds_postgres.ha_storage_multiplier",
  pg_storage_gb_month: "aws.rds_postgres.storage_gb_month",
  pg_iops_month: "aws.rds_postgres.iops_month",
  pg_backup_gb_month: "aws.rds_postgres.backup_gb_month",
  cache_nano_hour: "aws.elasticache_redis.nano_hour",
  cache_small_hour: "aws.elasticache_redis.small_hour",
  cache_standard_hour: "aws.elasticache_redis.standard_hour",
  cache_performance_hour: "aws.elasticache_redis.performance_hour",
  cache_ha_multiplier: "aws.elasticache_redis.ha_multiplier",
  object_storage_gb_month: "aws.s3.storage_gb_month",
  object_get_million: "aws.s3.get_million",
  object_put_million: "aws.s3.put_million",
  queue_requests_million: "aws.sqs.requests_million",
  lb_hour: "aws.alb.hour",
  lb_capacity_unit_hour: "aws.alb.lcu_hour",
  nat_hour: "aws.nat_gateway.hour",
  nat_gb: "aws.nat_gateway.gb",
  ipv4_hour: "aws.ipv4.hour",
  egress_internet_gb: "aws.data_transfer.internet_gb",
  egress_inter_region_gb: "aws.data_transfer.inter_region_gb",
  block_gb_month: "aws.ebs.gp3_gb_month",
  block_iops_month: "aws.ebs.gp3_iops_month",
  block_snapshot_gb_month: "aws.ebs.snapshot_gb_month",
  dns_zone_month: "aws.route53.zone_month",
  dns_queries_million: "aws.route53.queries_million",
  cert_month: "aws.acm.public_cert_month",
  logs_ingest_gb: "aws.cloudwatch.logs_ingest_gb",
};

const AZURE_SKUS: RoleMap = {
  container_vcpu_hour: "azure.container_apps.vcpu_hour",
  container_gb_hour: "azure.container_apps.gb_hour",
  vm_small_hour: "azure.vm.small_hour",
  vm_medium_hour: "azure.vm.medium_hour",
  vm_large_hour: "azure.vm.large_hour",
  pg_nano_hour: "azure.postgres_flexible.nano_hour",
  pg_small_hour: "azure.postgres_flexible.small_hour",
  pg_standard_hour: "azure.postgres_flexible.standard_hour",
  pg_performance_hour: "azure.postgres_flexible.performance_hour",
  pg_ha_multiplier: "azure.postgres_flexible.ha_multiplier",
  pg_ha_storage_multiplier: "azure.postgres_flexible.ha_storage_multiplier",
  pg_storage_gb_month: "azure.postgres_flexible.storage_gb_month",
  pg_iops_month: "azure.postgres_flexible.iops_month",
  pg_backup_gb_month: "azure.postgres_flexible.backup_gb_month",
  cache_nano_hour: "azure.redis.nano_hour",
  cache_small_hour: "azure.redis.small_hour",
  cache_standard_hour: "azure.redis.standard_hour",
  cache_performance_hour: "azure.redis.performance_hour",
  cache_ha_multiplier: "azure.redis.ha_multiplier",
  object_storage_gb_month: "azure.blob.storage_gb_month",
  object_get_million: "azure.blob.get_million",
  object_put_million: "azure.blob.put_million",
  queue_requests_million: "azure.storage_queue.requests_million",
  lb_hour: "azure.app_gateway.hour",
  lb_capacity_unit_hour: "azure.app_gateway.lcu_hour",
  nat_hour: "azure.nat_gateway.hour",
  nat_gb: "azure.nat_gateway.gb",
  ipv4_hour: "azure.public_ip.hour",
  egress_internet_gb: "azure.bandwidth.internet_gb",
  egress_inter_region_gb: "azure.bandwidth.inter_region_gb",
  block_gb_month: "azure.managed_disk.ssd_gb_month",
  block_iops_month: "azure.managed_disk.iops_month",
  block_snapshot_gb_month: "azure.managed_disk.snapshot_gb_month",
  dns_zone_month: "azure.dns.zone_month",
  dns_queries_million: "azure.dns.queries_million",
  cert_month: "azure.managed_cert.public_cert_month",
  logs_ingest_gb: "azure.log_analytics.logs_ingest_gb",
};

const GCP_SKUS: RoleMap = {
  container_vcpu_hour: "gcp.cloud_run.vcpu_hour",
  container_gb_hour: "gcp.cloud_run.gb_hour",
  vm_small_hour: "gcp.compute_engine.small_hour",
  vm_medium_hour: "gcp.compute_engine.medium_hour",
  vm_large_hour: "gcp.compute_engine.large_hour",
  pg_nano_hour: "gcp.cloud_sql_postgres.nano_hour",
  pg_small_hour: "gcp.cloud_sql_postgres.small_hour",
  pg_standard_hour: "gcp.cloud_sql_postgres.standard_hour",
  pg_performance_hour: "gcp.cloud_sql_postgres.performance_hour",
  pg_ha_multiplier: "gcp.cloud_sql_postgres.ha_multiplier",
  pg_ha_storage_multiplier: "gcp.cloud_sql_postgres.ha_storage_multiplier",
  pg_storage_gb_month: "gcp.cloud_sql_postgres.storage_gb_month",
  pg_iops_month: "gcp.cloud_sql_postgres.iops_month",
  pg_backup_gb_month: "gcp.cloud_sql_postgres.backup_gb_month",
  cache_nano_hour: "gcp.memorystore_redis.nano_hour",
  cache_small_hour: "gcp.memorystore_redis.small_hour",
  cache_standard_hour: "gcp.memorystore_redis.standard_hour",
  cache_performance_hour: "gcp.memorystore_redis.performance_hour",
  cache_ha_multiplier: "gcp.memorystore_redis.ha_multiplier",
  object_storage_gb_month: "gcp.gcs.storage_gb_month",
  object_get_million: "gcp.gcs.get_million",
  object_put_million: "gcp.gcs.put_million",
  queue_requests_million: "gcp.cloud_tasks.requests_million",
  lb_hour: "gcp.load_balancing.forwarding_rule_hour",
  lb_processed_gb: "gcp.load_balancing.processed_gb",
  nat_hour: "gcp.cloud_nat.hour",
  nat_gb: "gcp.cloud_nat.gb",
  ipv4_hour: "gcp.ipv4.hour",
  egress_internet_gb: "gcp.network.internet_gb",
  egress_inter_region_gb: "gcp.network.inter_region_gb",
  block_gb_month: "gcp.pd_balanced.gb_month",
  block_iops_month: "gcp.pd_balanced.iops_month",
  block_snapshot_gb_month: "gcp.pd_balanced.snapshot_gb_month",
  dns_zone_month: "gcp.cloud_dns.zone_month",
  dns_queries_million: "gcp.cloud_dns.queries_million",
  cert_month: "gcp.managed_cert.public_cert_month",
  logs_ingest_gb: "gcp.cloud_logging.logs_ingest_gb",
};

const OCI_SKUS: RoleMap = {
  container_vcpu_hour: "oci.container_instances.vcpu_hour",
  container_gb_hour: "oci.container_instances.gb_hour",
  vm_small_hour: "oci.compute.small_hour",
  vm_medium_hour: "oci.compute.medium_hour",
  vm_large_hour: "oci.compute.large_hour",
  pg_nano_hour: "oci.postgres.nano_hour",
  pg_small_hour: "oci.postgres.small_hour",
  pg_standard_hour: "oci.postgres.standard_hour",
  pg_performance_hour: "oci.postgres.performance_hour",
  pg_ha_multiplier: "oci.postgres.ha_multiplier",
  pg_ha_storage_multiplier: "oci.postgres.ha_storage_multiplier",
  pg_storage_gb_month: "oci.postgres.storage_gb_month",
  pg_iops_month: "oci.postgres.iops_month",
  pg_backup_gb_month: "oci.postgres.backup_gb_month",
  cache_nano_hour: "oci.redis.nano_hour",
  cache_small_hour: "oci.redis.small_hour",
  cache_standard_hour: "oci.redis.standard_hour",
  cache_performance_hour: "oci.redis.performance_hour",
  cache_ha_multiplier: "oci.redis.ha_multiplier",
  object_storage_gb_month: "oci.object_storage.storage_gb_month",
  object_get_million: "oci.object_storage.get_million",
  object_put_million: "oci.object_storage.put_million",
  queue_requests_million: "oci.queue.requests_million",
  lb_hour: "oci.flexible_lb.hour",
  lb_capacity_unit_hour: "oci.flexible_lb.lcu_hour",
  nat_hour: "oci.nat_gateway.hour",
  nat_gb: "oci.nat_gateway.gb",
  ipv4_hour: "oci.public_ip.hour",
  egress_internet_gb: "oci.network.internet_gb",
  egress_inter_region_gb: "oci.network.inter_region_gb",
  block_gb_month: "oci.block_volume.gb_month",
  block_iops_month: "oci.block_volume.iops_month",
  block_snapshot_gb_month: "oci.block_volume.snapshot_gb_month",
  dns_zone_month: "oci.dns.zone_month",
  dns_queries_million: "oci.dns.queries_million",
  cert_month: "oci.certificates.public_cert_month",
  logs_ingest_gb: "oci.logging.logs_ingest_gb",
};

const ZENITH_SKUS: RoleMap = {
  container_vcpu_hour: "zenith.container.vcpu_hour",
  container_gb_hour: "zenith.container.gb_hour",
  pg_nano_hour: "zenith.postgres.nano_hour",
  pg_small_hour: "zenith.postgres.small_hour",
  pg_standard_hour: "zenith.postgres.standard_hour",
  pg_performance_hour: "zenith.postgres.performance_hour",
  pg_ha_multiplier: "zenith.postgres.ha_multiplier",
  pg_ha_storage_multiplier: "zenith.postgres.ha_storage_multiplier",
  pg_storage_gb_month: "zenith.postgres.storage_gb_month",
  pg_iops_month: "zenith.postgres.iops_month",
  pg_backup_gb_month: "zenith.postgres.backup_gb_month",
  cache_nano_hour: "zenith.redis.nano_hour",
  cache_small_hour: "zenith.redis.small_hour",
  cache_standard_hour: "zenith.redis.standard_hour",
  cache_performance_hour: "zenith.redis.performance_hour",
  cache_ha_multiplier: "zenith.redis.ha_multiplier",
  object_storage_gb_month: "zenith.object_storage.storage_gb_month",
  object_get_million: "zenith.object_storage.get_million",
  object_put_million: "zenith.object_storage.put_million",
  queue_requests_million: "zenith.queue.requests_million",
  lb_hour: "zenith.lb.hour",
  nat_hour: "zenith.nat.hour",
  nat_gb: "zenith.nat.gb",
  ipv4_hour: "zenith.ipv4.hour",
  egress_internet_gb: "zenith.network.internet_gb",
  egress_inter_region_gb: "zenith.network.inter_region_gb",
  dns_zone_month: "zenith.dns.zone_month",
  dns_queries_million: "zenith.dns.queries_million",
  cert_month: "zenith.certificates.public_cert_month",
  logs_ingest_gb: "zenith.logs.logs_ingest_gb",
};

export const SKU_ROLE_MAP: Readonly<Record<string, Readonly<RoleMap>>> = {
  aws: AWS_SKUS,
  azure: AZURE_SKUS,
  gcp: GCP_SKUS,
  oci: OCI_SKUS,
  zenith: ZENITH_SKUS,
};

/** The catalog SKU for a role on a provider, or undefined when that provider has no such role. */
export function skuFor(provider: string, role: SkuRole): string | undefined {
  return SKU_ROLE_MAP[provider]?.[role];
}
