/**
 * Deterministic plain-text explanation of a placement result (ADR-0013).
 *
 * Every number in the text is read from the `PlacementResult`; nothing is
 * computed from outside it, nothing is generated by a model, and the same
 * result always yields the same text. That makes it safe to hand to a model
 * (or a user) as ground truth: the model may phrase it, it may not change it.
 * Component addresses and residency tokens are copied verbatim from the
 * inputs; treat them as data, never as instructions.
 */
import type { PlacementCandidate, PlacementResult } from "@/lib/placement/types";

const money = (x: number) => `${x < 0 ? "-" : ""}$${Math.abs(x).toFixed(2)}`;
const signed = (x: number) => `${x >= 0 ? "+" : "-"}${money(Math.abs(x))}`;
const cmp = (a: string, b: string) => (a < b ? -1 : a > b ? 1 : 0);

function reasonCategory(reason: string): string {
  const i = reason.indexOf(":");
  return i > 0 ? reason.slice(0, i) : "other";
}

/** Rejected candidates per cause (a candidate with two reasons of one cause counts once for that cause). */
function categoryCounts(rejected: PlacementResult["rejected"]): string {
  const cats = new Map<string, number>();
  for (const r of rejected) for (const c of new Set(r.reasons.map(reasonCategory))) cats.set(c, (cats.get(c) ?? 0) + 1);
  return [...cats.entries()].sort(([a], [b]) => cmp(a, b)).map(([k, n]) => `${k} ${n}`).join(", ");
}

function siteSummary(c: PlacementCandidate): string[] {
  const bySite = new Map<string, string[]>();
  for (const [addr, a] of Object.entries(c.assignments)) {
    const key = `${a.provider} ${a.region}`;
    bySite.set(key, [...(bySite.get(key) ?? []), addr]);
  }
  return [...bySite.entries()]
    .sort(([a], [b]) => cmp(a, b))
    .map(([site, addrs]) => `  ${site}: ${addrs.sort(cmp).join(", ")}`);
}

function latencyLine(c: PlacementCandidate): string {
  const parts = Object.entries(c.latencyMs)
    .sort(([a], [b]) => cmp(a, b))
    .map(([u, ms]) => `${u} ${ms} ms`);
  return parts.length > 0 ? parts.join(", ") : "not estimated";
}

function versus(chosen: PlacementCandidate, alt: PlacementCandidate): string {
  const dCost = alt.cost.monthlyUsd - chosen.cost.monthlyUsd;
  const pctText = chosen.cost.monthlyUsd > 0 ? `${dCost >= 0 ? "+" : "-"}${Math.abs(Math.round((dCost / chosen.cost.monthlyUsd) * 1000) / 10)}%` : "";
  const maxC = Math.max(...Object.values(chosen.latencyMs), 0);
  const maxA = Math.max(...Object.values(alt.latencyMs), 0);
  const why: string[] = [];
  const bd = (k: string, c: PlacementCandidate) => c.scoreBreakdown[k] ?? 0;
  if (bd("costPenalty", alt) > bd("costPenalty", chosen)) why.push(`costs ${money(dCost)} more per month`);
  else if (dCost < 0) why.push(`is ${money(-dCost)} cheaper but scores worse elsewhere`);
  if (bd("latencyPenalty", alt) + bd("overshootPenalty", alt) > bd("latencyPenalty", chosen) + bd("overshootPenalty", chosen)) {
    why.push(`is slower for the worst user region (${maxA} ms vs ${maxC} ms estimated p95)`);
  }
  if (bd("complexityPenalty", alt) > bd("complexityPenalty", chosen)) why.push("adds operational complexity (extra provider or region)");
  if (bd("preferenceBonus", alt) > bd("preferenceBonus", chosen)) why.push("matches the provider preference less");
  const reason = why.length > 0 ? why.join("; ") : "has a higher combined score";
  return `  ${alt.id}: ${money(alt.cost.monthlyUsd)}/month (${signed(dCost)}${pctText ? `, ${pctText}` : ""} vs the recommendation), worst-region p95 ${maxA} ms, score ${alt.score} vs ${chosen.score}. Not chosen because it ${reason}.`;
}

export interface ExplainOptions {
  /** alternatives to compare against (default 3) */
  alternatives?: number;
  /** cost lines to list (default 6) */
  costLines?: number;
}

export function explainPlacement(result: PlacementResult, options: ExplainOptions = {}): string {
  const lines: string[] = [];
  const chosen = result.chosen;

  if (!chosen) {
    lines.push("No placement satisfies the constraints.");
    if (result.rejected.length > 0) lines.push(`Rejected candidates by cause: ${categoryCounts(result.rejected)}.`);
    for (const r of result.rejected.slice(0, 5)) lines.push(`  ${r.id}: ${r.reasons.join("; ")}`);
    if (result.rejected.length > 5) lines.push(`  ... and ${result.rejected.length - 5} more rejected candidates.`);
    lines.push("Loosen the budget, residency, availability or pins, or fix the input problem above, and solve again.");
    lines.push(`Catalog ${result.catalogVersion}. Seed ${result.deterministicSeed.slice(0, 12)}.`);
    return lines.join("\n");
  }

  lines.push(`Recommended placement: ${chosen.id}, estimated ${money(chosen.cost.monthlyUsd)} per month (an estimate from catalog ${result.catalogVersion}, not an invoice).`);
  lines.push("Where things run:");
  lines.push(...siteSummary(chosen));
  lines.push(`Estimated p95 latency by user region: ${latencyLine(chosen)} (approximate).`);
  if (chosen.availabilityZones !== undefined) lines.push(`Availability zones used per region: ${chosen.availabilityZones}.`);
  const overrides = Object.entries(chosen.specOverrides ?? {}).sort(([a], [b]) => cmp(a, b));
  if (overrides.length > 0) {
    lines.push("Settings changed to meet the constraints: " + overrides.map(([addr, o]) => `${addr} ${Object.entries(o).sort(([a], [b]) => cmp(a, b)).map(([k, v]) => `${k}=${String(v)}`).join(", ")}`).join("; ") + ".");
  }

  const top = [...chosen.cost.lines].sort((a, b) => b.monthlyUsd - a.monthlyUsd || cmp(a.description + (a.address ?? ""), b.description + (b.address ?? ""))).slice(0, options.costLines ?? 6);
  lines.push("Largest cost lines:");
  for (const l of top) lines.push(`  ${money(l.monthlyUsd)}  ${l.description}${l.address ? ` (${l.address})` : ""}: ${l.basis}`);
  lines.push(`Included: ${chosen.cost.included.join("; ")}.`);
  lines.push(`Not included: ${chosen.cost.excluded.length} items, including taxes, discounts, free tiers and cross-AZ transfer (see the estimate).`);

  if (chosen.crossBoundary.length > 0) {
    lines.push("Cross-boundary traffic: " + chosen.crossBoundary.map((x) => `${x.from} -> ${x.to} (${x.kind === "cross_cloud" ? "cross-cloud" : "cross-region"}, ${money(x.egressUsdMonthly)}/month, +${x.addedLatencyMs} ms)`).join("; ") + ".");
  }

  const alts = result.alternatives.slice(0, options.alternatives ?? 3);
  if (alts.length > 0) {
    lines.push("Compared with the alternatives:");
    for (const a of alts) lines.push(versus(chosen, a));
  }

  if (result.rejected.length > 0) {
    lines.push(`${result.rejected.length} candidates were rejected by hard constraints (${categoryCounts(result.rejected)}).`);
    const budgetExample = result.rejected.find((r) => r.reasons.some((x) => x.startsWith("budget:")));
    if (budgetExample) lines.push(`  Example: ${budgetExample.id}: ${budgetExample.reasons.find((x) => x.startsWith("budget:"))}`);
  }

  if (chosen.warnings.length > 0) {
    lines.push("Cautions:");
    for (const w of chosen.warnings) lines.push(`  ${w}`);
  }
  lines.push(`Catalog ${result.catalogVersion}. Seed ${result.deterministicSeed.slice(0, 12)}.`);
  return lines.join("\n");
}
