/**
 * Evidence levels for every observability source (spec §42, architecture
 * invariant 8: honest capability labels).
 *
 * The capability matrix in the docs is generated from tables like this one, so
 * a source can never be described as better verified than it is:
 *
 *   real      — exercised against the real provider in a live acceptance run
 *   emulated  — exercised against an emulator (LocalStack, kind, PGlite)
 *   contract  — only mocked SDK / fake-HTTP contract tests
 *   simulated — generated data (sandbox); never presented as real
 *
 * As of this commit NOTHING observability reads has been run against a real
 * CloudWatch, Kubernetes API server, Prometheus or Loki (blocker B-AWS-LIVE:
 * no AWS credentials on the build machine; no cluster or Docker either). The
 * AWS clients are exercised through aws-sdk-client-mock, Kubernetes through a
 * fake `CoreV1Api`, Prometheus and Loki through a local fake HTTP server that
 * implements the documented response shapes. The sandbox source is `simulated`
 * by construction.
 *
 * Do not raise a level here without a recorded live/emulated run.
 */
import type { EvidenceLevel } from "@/lib/drivers/types";

export interface SourceEvidence {
  level: EvidenceLevel;
  /** what backs the level, in plain words */
  basis: string;
}

export const SOURCE_EVIDENCE: Readonly<Record<string, SourceEvidence>> = {
  "sandbox.logsim": { level: "simulated", basis: "generated by @/lib/logsim from deployment records; exercised against the real logsim over a temp store" },
  "aws.cloudwatch-logs": { level: "contract", basis: "aws-sdk-client-mock only (FilterLogEvents, StartQuery/GetQueryResults/StopQuery)" },
  "aws.cloudwatch-metrics": { level: "contract", basis: "aws-sdk-client-mock only (GetMetricData)" },
  "aws.events": { level: "contract", basis: "aws-sdk-client-mock only (ECS DescribeServices events and deployments)" },
  "aws.health": { level: "contract", basis: "aws-sdk-client-mock only (ECS DescribeServices/ListTasks/DescribeTasks, ELBv2 DescribeTargetHealth/DescribeTargetGroups/DescribeLoadBalancers, RDS DescribeDBInstances)" },
  kubernetes: { level: "contract", basis: "fake CoreV1Api and KubeConfig; method names checked against the installed @kubernetes/client-node v2" },
  prometheus: { level: "contract", basis: "local fake HTTP server implementing /api/v1/query_range" },
  loki: { level: "contract", basis: "local fake HTTP server implementing /loki/api/v1/query_range" },
};
