import { describe,it,expect,beforeAll } from 'vitest';
import { generateKeyPair, SignJWT, exportJWK, createLocalJWKSet } from 'jose';
import { verifyOAuth, bindGrant, oauthConfig, type OAuthConfig } from '../src/lib/agent-access/control/oauth';
import { Journal, type Principal } from '../src/lib/agent-access/control/journal';
const config:OAuthConfig={issuer:'https://auth.example.test',jwksUrl:'https://auth.example.test/jwks',resource:'https://zenith.example.test/api/agent/v2/mcp',clientClaim:'client_id'};
let pair:Awaited<ReturnType<typeof generateKeyPair>>, key:ReturnType<typeof createLocalJWKSet>;
beforeAll(async()=>{pair=await generateKeyPair('ES256');const jwk=await exportJWK(pair.publicKey);key=createLocalJWKSet({keys:[{...jwk,kid:'fixture',alg:'ES256'}]});});
async function token(overrides:Record<string,unknown>={}){const now=Math.floor(Date.now()/1000);return new SignJWT({sub:'user_1',iss:config.issuer,aud:config.resource,iat:now,exp:now+300,client_id:'codex-fixture',scope:'zenith:read zenith:plan zenith:write',...overrides}).setProtectedHeader({alg:'ES256',kid:'fixture',typ:'at+jwt'}).sign(pair.privateKey);}
const principal:Principal&{clientId:string;revoked?:boolean}={subject:'user_1',integrationId:'integration_1',workspaceId:'w',projectIds:['p'],appIds:['app'],scopes:['read','plan','write','publish'],expiresAt:new Date(Date.now()+3600000).toISOString(),clientId:'codex-fixture',oauthIssuer:config.issuer};
describe('OAuth resource binding',()=>{
 it('verifies the exact issuer, resource, lifetime and client',async()=>{const who=await verifyOAuth(await token(),config,key);expect(who.subject).toBe('user_1');expect(who.clientId).toBe('codex-fixture');expect(who.scopes).toEqual(['read','plan','write']);});
 for(const [name,claims] of Object.entries({foreignAudience:{aud:'https://other.test'},foreignIssuer:{iss:'https://other.test'},expired:{exp:1},futureIssued:{iat:Math.floor(Date.now()/1000)+120},longLived:{exp:Math.floor(Date.now()/1000)+7200},demo:{sub:'local'},noClient:{client_id:null},noRead:{scope:'zenith:write'},noExpiry:{exp:undefined}}))it(`rejects ${name}`,async()=>{await expect(verifyOAuth(await token(claims),config,key)).rejects.toBeDefined();});
 it('rejects wrong signatures and oversized tokens',async()=>{const wrong=await generateKeyPair('ES256');const bad=await new SignJWT({}).setProtectedHeader({alg:'ES256',kid:'fixture'}).sign(wrong.privateKey);await expect(verifyOAuth(bad,config,key)).rejects.toMatchObject({code:'invalid_token'});await expect(verifyOAuth('x'.repeat(16385),config,key)).rejects.toMatchObject({code:'invalid_token'});});
 it('intersects token scopes with a live issuer-bound resource grant',async()=>{const identity=await verifyOAuth(await token(),config,key);const who=bindGrant(identity,principal);expect(who.scopes).toEqual(['read','plan','write']);expect(who.expiresAt).toBe(identity.expiresAt);expect(who.projectIds).toEqual(['p']);});
 it('fails on absent, revoked, expired, wrong-user/client/issuer grants',async()=>{const identity=await verifyOAuth(await token(),config,key);for(const bad of [undefined,{...principal,revoked:true},{...principal,expiresAt:new Date(0).toISOString()},{...principal,subject:'other'},{...principal,clientId:'other'},{...principal,oauthIssuer:'https://other.test'}])expect(()=>bindGrant(identity,bad)).toThrow();});
 it('revocation persists and is applied on the next grant lookup',async()=>{const journal=new Journal(':memory:');try{const identity=await verifyOAuth(await token(),config,key);journal.setGrant(principal);expect(bindGrant(identity,journal.getGrant('user_1','codex-fixture','w')).subject).toBe('user_1');journal.setGrant({...principal,revoked:true});expect(()=>bindGrant(identity,journal.getGrant('user_1','codex-fixture','w'))).toThrow();}finally{journal.close();}});
 it('requires trusted HTTPS configuration and never derives an issuer from a JWT',()=>{expect(oauthConfig({},'https://zenith.example.test')).toBeUndefined();for(const values of [{ZENITH_AGENT_OAUTH_ISSUER:'http://localhost'}, {ZENITH_AGENT_OAUTH_ISSUER:'https://auth.test',ZENITH_AGENT_OAUTH_JWKS:'https://user:password@auth.test/jwks'}, {ZENITH_AGENT_OAUTH_ISSUER:'https://auth.test',ZENITH_AGENT_OAUTH_JWKS:'https://auth.test/jwks',ZENITH_AGENT_OAUTH_CLIENT_CLAIM:'sub'}])expect(()=>oauthConfig(values,'https://zenith.example.test')).toThrow();});
});
