import { describe,it,expect } from 'vitest';
import { Journal,type Principal,type Proposal,digest } from '../src/lib/agent-access/control/journal';
const user:Principal={subject:'alice',integrationId:'codex',workspaceId:'w',projectIds:['p'],environmentIds:['e'],appIds:['app'],scopes:['read','plan','write','publish'],expiresAt:new Date(Date.now()+3600000).toISOString()};
const target={workspaceId:'w',projectId:'p',environmentId:'e'};
describe('upload and review authority',()=>{
 it('binds uploaded bytes to exact user, workspace, project, app and digest',()=>{const j=new Journal(':memory:');try{const data=Buffer.from('fixture bytes'),stored=j.putUpload(user,target,'app',data);expect(j.upload(user,target,'app',stored.uploadId,stored.sha256)).toEqual(data);for(const u of [{...user,subject:'other'},{...user,workspaceId:'other'},{...user,projectIds:[]},{...user,appIds:[]},{...user,scopes:['read']}])expect(()=>j.upload(u,target,'app',stored.uploadId,stored.sha256)).toThrow();expect(()=>j.upload(user,target,'app',stored.uploadId,'0'.repeat(64))).toThrow();}finally{j.close();}});
 it('refuses expired uploads and bounds the active upload count',()=>{let now=Date.now();const j=new Journal(':memory:',()=>now);try{const first=j.putUpload(user,target,'app',Buffer.from('one'));for(let i=1;i<20;i++)j.putUpload(user,target,'app',Buffer.from('fixture'));expect(()=>j.putUpload(user,target,'app',Buffer.from('overflow'))).toThrow();now+=3600001;expect(()=>j.upload({...user,expiresAt:new Date(now+3600000).toISOString()},target,'app',first.uploadId,first.sha256)).toThrow();}finally{j.close();}});
 it('rejects empty and oversized archives before storing bytes',()=>{const j=new Journal(':memory:');try{expect(()=>j.putUpload(user,target,'app',Buffer.alloc(0))).toThrow();expect(()=>j.putUpload(user,target,'app',Buffer.alloc(20*1024*1024+1))).toThrow();}finally{j.close();}});
 it('permits a separately verified administrator review without impersonating the requester',()=>{const j=new Journal(':memory:');try{const p:Proposal={action:'deploy.apply',input:{},target,requestKey:'request-123',fingerprint:'exact-state',plan:{approvalRole:'admin'}};const op=j.prepare(user,p);j.review(op.id,user.subject,'w',op.digest,true,'admin_1','admin');const claim=j.claim(user,op.id,'exact-state');expect(claim.claimed).toBe(true);expect(claim.operation.subject).toBe('alice');expect(claim.operation.approvedBy).toBe('admin_1');expect(claim.operation.executedByIntegration).toBe('codex');}finally{j.close();}});
 it('finds a retried preparation without permitting another subject to discover it',()=>{const j=new Journal(':memory:');try{const p:Proposal={action:'deploy.apply',input:{},target,requestKey:'request-123',clientInputDigest:digest({input:'original'}),fingerprint:'state',plan:{}};const op=j.prepare(user,p);expect(j.findRequest({...user,integrationId:'claude'},p.requestKey)?.id).toBe(op.id);expect(j.findRequest({...user,subject:'other'},p.requestKey)).toBeUndefined();}finally{j.close();}});
});
