variable "zenith_issuer_host" {
  type        = string
  default     = ""
  description = <<-EOT
    The Zenith OIDC issuer WITHOUT https:// - host and path, for example
    app.tryzenith.cloud/api/oidc. Leave empty only if you use AssumeRole mode.
  EOT

  validation {
    condition     = can(regex("^$|^[a-z0-9]([a-z0-9.-]*[a-z0-9])?(:[0-9]{1,5})?(/[A-Za-z0-9._~/-]*)?$", var.zenith_issuer_host))
    error_message = "zenith_issuer_host must be a host (and optional path) without a scheme, e.g. app.tryzenith.cloud/api/oidc."
  }
}

variable "zenith_oidc_subject" {
  type        = string
  default     = ""
  description = "The exact token subject Zenith presents: zenith:ws:<workspace>:conn:<connection>. Shown by Zenith when you connect the account."

  validation {
    condition     = can(regex("^$|^zenith:ws:[A-Za-z0-9._-]{1,128}:conn:[A-Za-z0-9._-]{1,128}$", var.zenith_oidc_subject))
    error_message = "zenith_oidc_subject must look like zenith:ws:<workspace>:conn:<connection> (no wildcards)."
  }
}

variable "create_oidc_provider" {
  type        = bool
  default     = true
  description = "Create the IAM OIDC provider for the issuer. Set false if it already exists in this account (one provider per issuer URL per account)."
}

variable "zenith_principal_arn" {
  type        = string
  default     = ""
  description = "Only for a Zenith control plane that itself runs on AWS: the principal allowed to call sts:AssumeRole. Empty for the OIDC path."

  validation {
    condition     = can(regex("^$|^arn:aws(-cn|-us-gov)?:iam::[0-9]{12}:(root|role/.+|user/.+)$", var.zenith_principal_arn))
    error_message = "zenith_principal_arn must be an IAM root/role/user ARN."
  }
}

variable "external_id" {
  type        = string
  default     = ""
  description = "Per-connection ExternalId generated by Zenith; required with zenith_principal_arn (confused-deputy protection). Not a password."

  validation {
    # RE2 caps repetition counts at 1000, so the 1224-character limit is a length check.
    condition     = var.external_id == "" || (length(var.external_id) >= 2 && length(var.external_id) <= 1224 && can(regex("^[A-Za-z0-9+=,.@:/_-]+$", var.external_id)))
    error_message = "external_id must be 2-1224 characters of [A-Za-z0-9+=,.@:/_-]."
  }
}

variable "environment_tag_value" {
  type        = string
  default     = "*"
  description = "Scope of the deploy role. \"*\" allows any Zenith environment (any resource tagged zenith:managed=true); an exact value confines it to resources tagged zenith:environment=<value>."

  validation {
    condition     = can(regex("^[A-Za-z0-9_.:/=+@*-]{1,128}$", var.environment_tag_value))
    error_message = "environment_tag_value must be 1-128 characters of [A-Za-z0-9_.:/=+@*-]."
  }
}

variable "name_suffix" {
  type        = string
  default     = ""
  description = "Optional suffix, starting with a hyphen (for example -team-a), so several Zenith connections can coexist in one account."

  validation {
    condition     = can(regex("^(-[a-z0-9-]{1,19})?$", var.name_suffix))
    error_message = "name_suffix must be empty or start with a hyphen followed by 1-19 lowercase letters, digits or hyphens."
  }
}

variable "route53_hosted_zone_arns" {
  type        = list(string)
  default     = []
  description = "Hosted zones Zenith may change DNS records in (arn:aws:route53:::hostedzone/Z...). Empty gives Zenith no DNS write access."

  validation {
    condition     = alltrue([for z in var.route53_hosted_zone_arns : can(regex("^arn:aws(-cn|-us-gov)?:route53:::hostedzone/[A-Z0-9]+$", z))])
    error_message = "Each entry must be a hosted zone ARN such as arn:aws:route53:::hostedzone/Z123EXAMPLE."
  }
}

variable "state_bucket_kms_key_arn" {
  type        = string
  default     = ""
  description = "Optional customer-managed KMS key for the state bucket (SSE-KMS). Empty uses AES256 (SSE-S3). The key policy must allow this account's IAM."

  validation {
    condition     = can(regex("^$|^arn:aws(-cn|-us-gov)?:kms:[a-z0-9-]+:[0-9]{12}:key/[A-Za-z0-9-]+$", var.state_bucket_kms_key_arn))
    error_message = "state_bucket_kms_key_arn must be a KMS key ARN."
  }
}

variable "tags" {
  type        = map(string)
  default     = {}
  description = "Extra tags for the bootstrap resources. Never use zenith:managed here: the bootstrap resources must stay outside the deploy role's reach."

  validation {
    condition     = !contains(keys(var.tags), "zenith:managed")
    error_message = "Do not set the zenith:managed tag on bootstrap resources."
  }
}
