// Package oci implements the runner-only OCI boundary. Keys and tokens remain
// in memory; jobs contain unsigned requests. Live tenancy behavior is unverified.
package oci

import (
	"embed"
	"encoding/json"
	"strings"
)

// These contracts are generated by scripts/generate-oci-allowlist.ts and checked
// against the TypeScript source by tests/runners/oci-contract.test.ts.
//
//go:embed testdata/allowlist.json testdata/services.json
var contracts embed.FS

type Rule struct {
	Service string `json:"service"`
	Method  string `json:"method"`
	Pattern string `json:"pattern"`
}

type Service struct {
	Host    string `json:"host"`
	Version string `json:"version"`
}

var rules = loadContract[map[string][]Rule]("allowlist")
var services = loadContract[map[string]Service]("services")

func loadContract[T any](name string) T {
	data, err := contracts.ReadFile("testdata/" + name + ".json")
	if err != nil {
		panic("missing embedded OCI contract")
	}
	var out T
	if json.Unmarshal(data, &out) != nil {
		panic("invalid embedded OCI contract")
	}
	return out
}

// Match returns a trusted path template, never the external resource names.
// secret.write remains in the shared contract but is refused by Prepare.
func Match(capability, service, method, path string) (string, bool) {
	if !PlainPath(path) || method == "DELETE" {
		return "", false
	}
	for _, rule := range rules[capability] {
		if rule.Service != service || rule.Method != method {
			continue
		}
		version := services[service].Version
		template := "/" + rule.Pattern
		if version != "" {
			template = "/" + version + template
		}
		want, have := strings.Split(template, "/"), strings.Split(path, "/")
		if len(want) != len(have) {
			continue
		}
		matches := true
		for i := range want {
			if want[i] != "{}" && want[i] != have[i] {
				matches = false
				break
			}
		}
		if matches {
			return template, true
		}
	}
	return "", false
}

func ResolveHost(service, region, endpointHost string) (string, error) {
	entry, ok := services[service]
	if !ok || !RegionID(region) {
		return "", ErrInvalidRequest
	}
	if service == "queue-data" {
		if !OracleHost(endpointHost) {
			return "", ErrInvalidRequest
		}
		return endpointHost, nil
	}
	if endpointHost != "" {
		return "", ErrInvalidRequest
	}
	return strings.ReplaceAll(entry.Host, "{region}", region), nil
}
