/**
 * Regenerate the committed provider lockfiles.
 *
 *   npx tsx src/lib/tofu/scripts/lock.ts                 # every provider
 *   npx tsx src/lib/tofu/scripts/lock.ts --only aws,random
 *
 * Each provider in `PROVIDER_PINS` is locked once with
 * `tofu providers lock -platform=…` for every platform in `LOCK_PLATFORMS`,
 * then each provider set's `locks/<set>.terraform.lock.hcl` is assembled from
 * those blocks. Providers not selected by `--only` keep the block already
 * committed. A provider whose download fails leaves every set that needs it
 * unchanged and the script exits non-zero after writing what succeeded.
 *
 * Also rewrites `locks.generated.ts`, the bundle-safe mirror of the `.hcl`
 * files (`tests/tofu/providers.test.ts` asserts they are identical).
 *
 * Needs network access to registry.opentofu.org and the providers' release
 * hosts; the cloud providers are large (aws ≈ 160 MB per platform).
 */
import { existsSync, readFileSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { resolveTofuBinary, checkTofuVersion } from "@/lib/tofu/binary";
import { generateLockfile } from "@/lib/tofu/lockgen";
import { assembleLockfile, splitLockBlocks, type LockedProvider } from "@/lib/tofu/lockfile";
import {
  EMPTY_LOCKFILE,
  PROVIDER_PINS,
  PROVIDER_SET_NAMES,
  PROVIDER_SET_PROVIDERS,
  lockfileSource,
  type ProviderLocalName,
  type ProviderSetName,
} from "@/lib/tofu/providers";

const here = path.dirname(fileURLToPath(import.meta.url));
const locksDir = path.resolve(here, "..", "locks");

function lockPath(set: ProviderSetName): string {
  return path.join(locksDir, `${set}.terraform.lock.hcl`);
}

function existingBlocks(): Map<string, LockedProvider> {
  const blocks = new Map<string, LockedProvider>();
  for (const set of PROVIDER_SET_NAMES) {
    const p = lockPath(set);
    if (!existsSync(p)) continue;
    for (const b of splitLockBlocks(readFileSync(p, "utf8"))) blocks.set(b.source, b);
  }
  return blocks;
}

async function main(): Promise<void> {
  const onlyArg = process.argv.find((a) => a.startsWith("--only="))?.slice("--only=".length) ?? (process.argv.includes("--only") ? process.argv[process.argv.indexOf("--only") + 1] : undefined);
  const all = Object.keys(PROVIDER_PINS) as ProviderLocalName[];
  const selected = onlyArg ? (onlyArg.split(",").map((s) => s.trim()).filter(Boolean) as ProviderLocalName[]) : all;
  for (const s of selected) {
    if (!(s in PROVIDER_PINS)) throw new Error(`Unknown provider "${s}". Known: ${all.join(", ")}`);
  }

  const bin = resolveTofuBinary();
  const info = await checkTofuVersion(bin);
  console.log(`tofu ${info.version} (${info.platform}) at ${bin}`);

  const blocks = existingBlocks();
  const failed: string[] = [];
  const incomplete: string[] = [];
  for (const name of selected) {
    const pin = PROVIDER_PINS[name];
    const started = Date.now();
    console.log(`locking ${pin.source} ${pin.version} …`);
    try {
      const { lockfile } = await generateLockfile({ bin, providers: [name] });
      const [block] = splitLockBlocks(lockfile);
      if (!block || block.source !== lockfileSource(name) || block.version !== pin.version) {
        throw new Error(`unexpected lock result for ${name}: ${block ? `${block.source} ${block.version}` : "no provider block"}`);
      }
      blocks.set(block.source, block);
      console.log(`  ok (${block.hashes.length} hashes, ${Math.round((Date.now() - started) / 1000)}s)`);
    } catch (err) {
      failed.push(name);
      console.error(`  FAILED: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  await mkdir(locksDir, { recursive: true });
  const generated: Record<string, string> = {};
  for (const set of PROVIDER_SET_NAMES) {
    const wanted = PROVIDER_SET_PROVIDERS[set];
    const parts: LockedProvider[] = [];
    let complete = true;
    for (const name of wanted) {
      const b = blocks.get(lockfileSource(name));
      // a block from an older pin is stale, treat as missing
      if (!b || b.version !== PROVIDER_PINS[name].version) complete = false;
      else parts.push(b);
    }
    if (!complete) {
      console.error(`set ${set}: incomplete (missing or stale providers) — not written`);
      incomplete.push(set);
      const prior = existsSync(lockPath(set)) ? readFileSync(lockPath(set), "utf8") : undefined;
      if (prior) generated[set] = prior;
      continue;
    }
    const content = wanted.length === 0 ? EMPTY_LOCKFILE : assembleLockfile(parts);
    await writeFile(lockPath(set), content);
    generated[set] = content;
    console.log(`set ${set}: wrote ${path.relative(process.cwd(), lockPath(set))}`);
  }

  const ts = `/**
 * GENERATED by src/lib/tofu/scripts/lock.ts — do not edit by hand.
 * Bundle-safe mirror of ./locks/<set>.terraform.lock.hcl (a runtime file read
 * would not survive bundling). tests/tofu/providers.test.ts asserts each entry
 * equals its .hcl file.
 */
export const LOCKFILES: Record<string, string> = ${JSON.stringify(generated, null, 2)};
`;
  await writeFile(path.join(here, "..", "locks.generated.ts"), ts);

  if (failed.length) {
    console.error(`\nIncomplete: ${failed.join(", ")}`);
    process.exitCode = 1;
  }
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
