/**
 * Per-service health for an environment.
 *
 * Honesty: this data is generated by Zenith's log simulator from the deployed
 * revision and a seeded PRNG. It is synthetic for EVERY provider — LocalStack
 * and AWS included — because no adapter reports real health yet. So the route
 * names the environment's actual provider rather than letting the UI assume
 * "sandbox", and `simulated` says plainly that nothing was measured.
 */
import { q } from "@/lib/db/store";
import { getProvider, providerRegistry } from "@/lib/providers/types";
import { logsimModule } from "@/lib/server/boot";
import { route, scopedEnvironment } from "@/lib/server/context";

export const dynamic = "force-dynamic";

export const GET = route<{ envId: string }>(async (_req, { envId }) => {
  // Bound to the caller's workspace through the owning project. An environment
  // id from another tenant answers the same 404 as one that never existed.
  const env = scopedEnvironment(envId);

  const providerId = q.connection(env.connectionId)?.provider ?? "sandbox";
  const provider = providerRegistry().has(providerId) ? getProvider(providerId) : undefined;
  const logsim = await logsimModule();

  return {
    environmentId: env.id,
    /**
     * True: nothing here was measured against running infrastructure.
     * When an adapter grows a real health check, this becomes
     * `!provider.reportsHealth` — the flag is on the wire either way.
     */
    simulated: true,
    /** who this environment actually deploys through, so nothing is misattributed */
    provider: { id: providerId, displayName: provider?.displayName ?? providerId },
    generatedBy: "Zenith's log simulator, from the deployed revision",
    services: logsim.environmentHealth?.(env.id) ?? {},
  };
});
