/**
 * Alert rules: a condition, an in-product record, and nothing else.
 *
 * Honesty rules, in order of importance:
 *
 *  - **Delivery does not exist.** Nothing here emails, pages or posts to Slack.
 *    A rule that fires writes an AlertEvent; the Observe screen and the client
 *    hook in `@/lib/client/alerts` are the only places it surfaces. Every plan
 *    and empty state says so, and docs/LIMITATIONS.md keeps saying it.
 *  - **Same inputs as the screens.** Health comes from `@/lib/logsim` — exactly
 *    what the health cards render — cost from the price table, deploy outcomes
 *    from the durable deployment records. An alert can never disagree with the
 *    page it sits on, because it reads the page's own data.
 *  - **Simulated stays labelled.** `AlertEvent.simulated` is true whenever the
 *    condition read generated or estimated data, which today is every kind
 *    except a deployment failure on a non-sandbox provider.
 *
 * Evaluation is derived, not remembered: the condition is recomputed from
 * durable records every time, so a restart re-derives the same answer. The only
 * thing stored is the event log — one open event per rule, closed when the
 * condition clears.
 *
 * ponytail: no per-rule schedule and no hysteresis. A rule is evaluated on the
 * one 15s timer and on read; a condition that flaps faster than that produces
 * one event per flap. Add a "for N consecutive evaluations" field to AlertRule
 * if that ever gets noisy.
 */
import { monthlyCostUsd } from "@/lib/cost/pricing";
import { db, q, save } from "@/lib/db/store";
import {
  id,
  type Actor,
  type AlertEvent,
  type AlertKind,
  type AlertRule,
  type Deployment,
  type DeploymentStatus,
  type Environment,
} from "@/lib/domain/types";
import { environmentHealth } from "@/lib/logsim";
import { log } from "@/lib/log";

/**
 * How often the background evaluator runs. Modest on purpose: the loop returns
 * immediately when the workspace has no rules, and one pass over every rule is
 * a health computation per environment — the same one the Observe page asks for
 * every 5 seconds while it is open. The timer is `unref`'d, so it never holds
 * the process open for a script or a test run.
 */
export const EVALUATION_INTERVAL_MS = 15_000;

/** Recent history kept alongside the open events in the summary response. */
const RECENT_EVENTS = 20;

const iso = (at: number) => new Date(at).toISOString();

/* --------------------------------- catalog -------------------------------- */

export interface ThresholdSpec {
  label: string;
  /** used when a rule leaves `threshold` unset */
  default: number;
  min: number;
  max: number;
  unit: string;
}

export interface AlertKindSpec {
  title: string;
  /** what the evaluator actually looks at, in one phrase */
  watches: string;
  severity: AlertEvent["severity"];
  threshold?: ThresholdSpec;
}

/** The vocabulary. UI copy, plan details and docs all read from here. */
export const ALERT_KINDS: Record<AlertKind, AlertKindSpec> = {
  health_degraded: {
    title: "A service is degraded",
    watches:
      "the health Orrery computes for every managed service in this environment, and the transitions it recorded in the last hour",
    severity: "medium",
  },
  deploy_failed: {
    title: "A deployment failed",
    watches: "the newest deployment to this environment that reached a final state",
    severity: "high",
  },
  budget_exceeded: {
    title: "Cost reached the budget",
    watches:
      "the estimated monthly cost of what is running here, against the environment's budget",
    severity: "medium",
    threshold: {
      label: "Fires at this percent of the budget",
      default: 100,
      min: 1,
      max: 500,
      unit: "%",
    },
  },
  replicas_below: {
    title: "Ready replicas below a floor",
    watches: "how many replicas of each managed service are passing their health probe",
    severity: "high",
    threshold: {
      label: "Minimum ready replicas per service",
      default: 1,
      min: 1,
      max: 10,
      unit: " replicas",
    },
  },
};

export const thresholdOf = (rule: Pick<AlertRule, "kind" | "threshold">): number | undefined => {
  const spec = ALERT_KINDS[rule.kind].threshold;
  if (!spec) return undefined;
  return rule.threshold ?? spec.default;
};

/* -------------------------------- conditions ------------------------------- */

export interface AlertCondition {
  firing: boolean;
  /** one line, written for both outcomes — the all-clear says why it is clear */
  summary: string;
  detail: string;
  severity: AlertEvent["severity"];
  /** true when the inputs were generated or estimated rather than measured */
  simulated: boolean;
}

const TERMINAL: DeploymentStatus[] = ["succeeded", "failed", "cancelled", "rolled_back"];

const SIMULATED_NOTE =
  "Health here is generated by Orrery's log simulator from the deployed revision — nothing was measured against a running process.";

const COST_NOTE = "Cost is an estimate from the price table, not a bill.";

/** Service names come from the revision that is actually running. */
function serviceName(env: Environment, serviceId: string): string {
  const revision = env.deployedRevisionId ? q.revision(env.deployedRevisionId) : undefined;
  return revision?.manifest.services.find((s) => s.id === serviceId)?.name ?? serviceId;
}

function newestFinished(environmentId: string): Deployment | undefined {
  return db()
    .deployments.filter((d) => d.environmentId === environmentId && TERMINAL.includes(d.status))
    .sort((a, b) => ((a.endedAt ?? a.createdAt) < (b.endedAt ?? b.createdAt) ? 1 : -1))[0];
}

function healthCondition(rule: AlertRule, env: Environment): AlertCondition {
  const services = Object.entries(environmentHealth(env.id));
  const degraded = services.filter(([, h]) => h.status === "degraded");
  const base = { severity: ALERT_KINDS[rule.kind].severity, simulated: true };

  if (services.length === 0)
    return {
      ...base,
      firing: false,
      summary: `Nothing is running in ${env.name}, so no service can be degraded.`,
      detail: `${env.name} has no deployed revision with managed services. Deploy it and this rule starts watching. ${SIMULATED_NOTE}`,
    };
  if (degraded.length === 0)
    return {
      ...base,
      firing: false,
      summary: `All ${services.length} managed service${services.length === 1 ? "" : "s"} in ${env.name} are healthy.`,
      detail: SIMULATED_NOTE,
    };

  const names = degraded.map(([sid]) => serviceName(env, sid));
  return {
    ...base,
    firing: true,
    summary: `${names.join(", ")} degraded in ${env.name}.`,
    detail: [
      ...degraded.map(([sid, h]) => `${serviceName(env, sid)}: ${h.reason}`),
      SIMULATED_NOTE,
    ].join(" "),
  };
}

function deployCondition(rule: AlertRule, env: Environment): AlertCondition {
  const last = newestFinished(env.id);
  const providerId = q.connection(env.connectionId)?.provider ?? "sandbox";
  // A sandbox deployment created nothing, so its failure is a simulated one.
  // Any other adapter really ran the steps that failed.
  const base = { severity: ALERT_KINDS[rule.kind].severity, simulated: providerId === "sandbox" };

  if (!last)
    return {
      ...base,
      firing: false,
      summary: `No deployment to ${env.name} has finished yet.`,
      detail: "This rule fires when the newest finished deployment ends in failure.",
    };
  if (last.status !== "failed")
    return {
      ...base,
      firing: false,
      summary: `The newest deployment to ${env.name} ${last.status}.`,
      detail: `${last.changeSummary || "The last deployment"} finished as ${last.status}.`,
    };

  const revision = q.revision(last.revisionId);
  return {
    ...base,
    firing: true,
    summary: `Deployment of r${revision?.number ?? "?"} to ${env.name} failed.`,
    detail: [
      last.error ?? "The deployment failed without recording an error.",
      `Open it under Deploys for the step that failed. This clears when a later deployment to ${env.name} finishes without failing.`,
    ].join(" "),
  };
}

function budgetCondition(rule: AlertRule, env: Environment): AlertCondition {
  const base = { severity: ALERT_KINDS[rule.kind].severity, simulated: true };
  const budget = env.policies.budgetUsdMonthly;
  if (!budget)
    return {
      ...base,
      firing: false,
      summary: `${env.name} has no budget, so there is nothing to compare against.`,
      detail:
        "Set a monthly budget in Settings → Environments for this rule to do anything. Until then it can never fire.",
    };

  const running = env.deployedRevisionId ? q.revision(env.deployedRevisionId) : undefined;
  const manifest = running?.manifest ?? q.project(env.projectId)?.workingManifest;
  if (!manifest)
    return {
      ...base,
      firing: false,
      summary: `${env.name} has no system to price.`,
      detail: "The project this environment belongs to no longer exists.",
    };

  const cost = monthlyCostUsd(manifest);
  const at = Math.round((cost / budget) * 100);
  const threshold = thresholdOf(rule)!;
  const what = running
    ? `r${running.number}, the revision running in ${env.name}`
    : `the working copy — nothing is deployed to ${env.name} yet`;
  const money = `$${cost.toFixed(2)} of the $${budget.toFixed(2)} budget (${at}%), priced from ${what}.`;

  return {
    ...base,
    firing: at >= threshold,
    summary:
      at >= threshold
        ? `${env.name} is at ${at}% of its budget (threshold ${threshold}%).`
        : `${env.name} is at ${at}% of its budget, under the ${threshold}% threshold.`,
    detail: `${money} ${COST_NOTE}`,
  };
}

function replicaCondition(rule: AlertRule, env: Environment): AlertCondition {
  const base = { severity: ALERT_KINDS[rule.kind].severity, simulated: true };
  const floor = thresholdOf(rule)!;
  const services = Object.entries(environmentHealth(env.id));
  if (services.length === 0)
    return {
      ...base,
      firing: false,
      summary: `Nothing is running in ${env.name}, so there are no replicas to count.`,
      detail: `Deploy ${env.name} and this rule starts watching. ${SIMULATED_NOTE}`,
    };

  const short = services.filter(([, h]) => h.replicasReady < floor);
  if (short.length === 0)
    return {
      ...base,
      firing: false,
      summary: `Every managed service in ${env.name} has at least ${floor} ready replica${floor === 1 ? "" : "s"}.`,
      detail: SIMULATED_NOTE,
    };

  return {
    ...base,
    firing: true,
    summary: `${short.map(([sid]) => serviceName(env, sid)).join(", ")} below ${floor} ready replica${floor === 1 ? "" : "s"} in ${env.name}.`,
    detail: [
      ...short.map(
        ([sid, h]) =>
          `${serviceName(env, sid)}: ${h.replicasReady} of ${h.replicasDesired} ready.`
      ),
      SIMULATED_NOTE,
    ].join(" "),
  };
}

/**
 * Evaluate one rule against the current state. Pure with respect to the store:
 * it reads, it never writes, and it never throws — the evaluator runs on a
 * timer, so a rule pointing at a deleted environment reports that instead.
 */
export function evaluateRule(rule: AlertRule): AlertCondition {
  const env = q.environment(rule.environmentId);
  if (!env)
    return {
      firing: false,
      summary: "The environment this rule watches no longer exists.",
      detail: `Delete this rule, or recreate the environment it was made for. It cannot fire while its environment is missing.`,
      severity: ALERT_KINDS[rule.kind].severity,
      simulated: true,
    };
  switch (rule.kind) {
    case "health_degraded":
      return healthCondition(rule, env);
    case "deploy_failed":
      return deployCondition(rule, env);
    case "budget_exceeded":
      return budgetCondition(rule, env);
    case "replicas_below":
      return replicaCondition(rule, env);
  }
}

/* --------------------------------- record --------------------------------- */

export const openEventFor = (ruleId: string): AlertEvent | undefined =>
  db().alertEvents.find((e) => e.ruleId === ruleId && !e.resolvedAt);

/**
 * Close a rule's open event, if it has one. Used when the condition clears and
 * when the rule stops watching (disabled, deleted) — a record that stays open
 * for a rule nobody is evaluating would be a lie.
 */
export function resolveOpen(ruleId: string, reason: string, at = Date.now()): boolean {
  const open = openEventFor(ruleId);
  if (!open) return false;
  open.resolvedAt = iso(at);
  open.resolvedReason = reason;
  return true;
}

/** One rule, one pass. Returns true when the event log changed. */
function applyRule(rule: AlertRule, at: number): boolean {
  if (!rule.enabled) return resolveOpen(rule.id, "The rule was turned off.", at);
  const cond = evaluateRule(rule);
  const open = openEventFor(rule.id);

  if (cond.firing && !open) {
    db().alertEvents.push({
      id: id(),
      ruleId: rule.id,
      projectId: rule.projectId,
      environmentId: rule.environmentId,
      firedAt: iso(at),
      summary: cond.summary,
      severity: cond.severity,
      detail: cond.detail,
      simulated: cond.simulated,
    });
    log.info("alert fired", { scope: "alerts", ruleId: rule.id, kind: rule.kind });
    return true;
  }
  if (!cond.firing && open) return resolveOpen(rule.id, cond.summary, at);
  return false;
}

/**
 * Evaluate a set of rules and persist any change. Saving only when something
 * actually changed is what keeps a 15s timer from rewriting state.json forever
 * in a workspace where nothing is wrong.
 */
function evaluate(rules: AlertRule[], at = Date.now()): number {
  let changed = 0;
  for (const rule of rules) if (applyRule(rule, at)) changed++;
  if (changed) save();
  return changed;
}

/** Everything, for the background pass. */
export const evaluateAll = (at = Date.now()): number => evaluate(db().alertRules, at);

/** One project, for a read of the alerts API — the page shows a fresh answer. */
export const evaluateProject = (projectId: string, at = Date.now()): number =>
  evaluate(
    db().alertRules.filter((r) => r.projectId === projectId),
    at
  );

/* --------------------------------- queries -------------------------------- */

export const rulesOf = (projectId: string, environmentId?: string): AlertRule[] =>
  db()
    .alertRules.filter(
      (r) => r.projectId === projectId && (!environmentId || r.environmentId === environmentId)
    )
    .sort((a, b) => (a.createdAt < b.createdAt ? -1 : 1));

export const requireRule = (ruleId: string): AlertRule => {
  const rule = db().alertRules.find((r) => r.id === ruleId);
  if (!rule)
    throw new Error(
      `Alert rule "${ruleId}" was not found. Reload Observe — someone may have deleted it.`
    );
  return rule;
};

export const requireEvent = (eventId: string): AlertEvent => {
  const event = db().alertEvents.find((e) => e.id === eventId);
  if (!event)
    throw new Error(
      `Alert "${eventId}" was not found. Reload Observe — the alert list may have moved on.`
    );
  return event;
};

/** Newest first, open events ahead of resolved ones. */
const byRecency = (a: AlertEvent, b: AlertEvent) => (a.firedAt < b.firedAt ? 1 : -1);

export function eventsOf(
  projectId: string,
  opts: { environmentId?: string; open?: boolean } = {}
): AlertEvent[] {
  return db()
    .alertEvents.filter(
      (e) =>
        e.projectId === projectId &&
        (!opts.environmentId || e.environmentId === opts.environmentId) &&
        (!opts.open || !e.resolvedAt)
    )
    .sort(byRecency);
}

/**
 * Open events first, then the most recent resolved ones. This is what the
 * Observe banner and the shell bell read: the open list is the thing that
 * matters, the tail is the record that a service *was* degraded.
 */
export function summaryFor(
  projectId: string,
  environmentId?: string
): { open: AlertEvent[]; recent: AlertEvent[] } {
  const all = eventsOf(projectId, { environmentId });
  return {
    open: all.filter((e) => !e.resolvedAt),
    recent: all.filter((e) => e.resolvedAt).slice(0, RECENT_EVENTS),
  };
}

/**
 * A page of history, newest first. The cursor is the sort key of the last row
 * returned, so a page is stable while new events arrive at the front.
 */
export function eventPage(opts: {
  projectId: string;
  environmentId?: string;
  limit: number;
  cursor?: string;
}): { events: AlertEvent[]; nextCursor?: string } {
  const key = (e: AlertEvent) => `${e.firedAt}|${e.id}`;
  const rows = eventsOf(opts.projectId, { environmentId: opts.environmentId }).filter(
    (e) => !opts.cursor || key(e) < opts.cursor
  );
  const events = rows.slice(0, opts.limit);
  return {
    events,
    nextCursor:
      rows.length > events.length && events.length > 0
        ? key(events[events.length - 1])
        : undefined,
  };
}

/** Acknowledge: a human says they have seen it. It does not close the event. */
export function acknowledge(eventId: string, actor: Actor, note?: string): AlertEvent {
  const event = requireEvent(eventId);
  event.acknowledgedAt = new Date().toISOString();
  event.acknowledgedBy = actor;
  if (note) event.acknowledgedNote = note;
  save();
  return event;
}

/* -------------------------------- evaluator ------------------------------- */

type G = typeof globalThis & { __orreryAlertTimer?: ReturnType<typeof setInterval> };

/**
 * Start the background pass. Idempotent, and `unref`'d so it never keeps the
 * process alive: this is a convenience for a server that is already running,
 * not a scheduler. Nothing is evaluated when the workspace has no rules.
 */
export function startAlertEvaluator(): void {
  const g = globalThis as G;
  if (g.__orreryAlertTimer) return;
  const pass = () => {
    try {
      if (db().alertRules.length === 0) return;
      evaluateAll();
    } catch (err) {
      // A broken rule must not kill the timer for every other rule.
      log.error("alert evaluation failed", { scope: "alerts", error: err });
    }
  };
  pass(); // re-derive open state immediately after a restart
  g.__orreryAlertTimer = setInterval(pass, EVALUATION_INTERVAL_MS);
  (g.__orreryAlertTimer as { unref?: () => void }).unref?.();
}
