/**
 * Credential broker contract (spec §11, ADR-0006).
 *
 * Zenith never stores customer long-lived cloud keys. A provider connection
 * stores only non-secret identifiers (role ARN, workload identity pool,
 * tenant/client ids); the broker exchanges them for short-lived credentials
 * at execution time, inside the trusted execution worker, for exactly one
 * operation, and hands the caller a *session* (client factories), never raw
 * key material.
 *
 * Two federation paths, both keyless:
 *   1. OIDC web identity (preferred, works for AWS, GCP, Azure): Zenith is an
 *      OIDC issuer (`<origin>/api/oidc`). The broker mints a ≤5-minute JWT
 *      whose `sub` is `zenith:ws:<workspaceId>:conn:<connectionId>` and
 *      exchanges it with the cloud's STS (AWS AssumeRoleWithWebIdentity, GCP
 *      STS token exchange + SA impersonation, Azure client assertion). The
 *      customer's trust policy pins the issuer, audience and exact `sub`.
 *   2. AWS AssumeRole with ExternalId from Zenith's own AWS principal (for a
 *      control plane that itself runs on AWS). ExternalId is per connection,
 *      generated by Zenith, and prevents confused-deputy.
 * Plus `runner`: credentials never leave the customer's network; jobs go to
 * the customer's zenith-runner, which uses its local workload identity.
 *
 * Invariants:
 *   - Credentials exist only in worker memory for the duration of the
 *     callback. They are never returned through REST/MCP, never logged, never
 *     written to the control store, never placed in Temporal workflow or
 *     activity payloads, never given to a model.
 *   - Every session is scoped: ≤ 1 hour (default 15 minutes), session-tagged
 *     with workspace/operation/capability, and — on AWS — narrowed with an
 *     inline session policy derived from the capability.
 *   - The broker refuses unless presented a valid capability grant whose
 *     workspace matches the connection's workspace.
 */
import type { CapabilityGrantClaims } from "@/lib/controlplane/types";

/* --------------------------- connection configs --------------------------- */

export type AuthMode = "oidc_web_identity" | "aws_assume_role" | "runner" | "kubeconfig_ref" | "static_dev";

export interface AwsConnectionConfig {
  provider: "aws";
  mode: "oidc_web_identity" | "aws_assume_role" | "runner" | "static_dev";
  accountId: string;
  /** role for read/observe capabilities */
  observeRoleArn: string;
  /** role for mutating capabilities; may equal observeRoleArn in dev */
  deployRoleArn: string;
  /** per-connection, Zenith-generated; required for aws_assume_role */
  externalId?: string;
  region: string;
  /** default 900, max 3600 */
  sessionDurationSec?: number;
  /** S3 bucket for OpenTofu state in the customer account */
  stateBucket?: string;
  /** KMS key for OpenTofu state encryption, optional */
  stateKmsKeyArn?: string;
  /** endpoint override — LocalStack only; refused for production environments */
  endpoint?: string;
  runnerId?: string;
}

export interface GcpConnectionConfig {
  provider: "gcp";
  mode: "oidc_web_identity" | "runner";
  projectId: string;
  /** projects/<num>/locations/global/workloadIdentityPools/<pool>/providers/<provider> */
  workloadIdentityProvider: string;
  observeServiceAccount: string;
  deployServiceAccount: string;
  region: string;
  runnerId?: string;
}

export interface AzureConnectionConfig {
  provider: "azure";
  mode: "oidc_web_identity" | "runner";
  tenantId: string;
  clientId: string;
  subscriptionId: string;
  region: string;
  runnerId?: string;
}

export interface OciConnectionConfig {
  provider: "oci";
  mode: "runner";
  tenancyOcid: string;
  compartmentOcid: string;
  region: string;
  runnerId: string;
}

export interface KubernetesConnectionConfig {
  provider: "kubernetes";
  mode: "kubeconfig_ref" | "runner" | "oidc_web_identity";
  /** API server URL */
  server: string;
  /** base64 PEM CA bundle (not secret) */
  caData?: string;
  /** vault reference to a service-account token or kubeconfig — never inline */
  credentialRef?: string;
  /** namespaces Zenith may manage; empty = only namespaces it creates */
  namespaces: string[];
  /** for EKS: cluster name + an AWS connection id used to mint the token */
  eks?: { clusterName: string; awsConnectionId: string };
  runnerId?: string;
}

export type ConnectionConfig =
  | AwsConnectionConfig
  | GcpConnectionConfig
  | AzureConnectionConfig
  | OciConnectionConfig
  | KubernetesConnectionConfig;

export interface ProviderConnection {
  id: string;
  workspaceId: string;
  /** the product-store CloudConnection this extends, when there is one */
  legacyConnectionId?: string;
  config: ConnectionConfig;
  status: "pending_verification" | "verified" | "failed" | "revoked";
  verifiedAt?: string;
  verificationDetail?: string;
  createdBy: string;
  createdAt: string;
  revokedAt?: string;
}

/* -------------------------------- sessions -------------------------------- */

/** An AWS SDK v3 client constructor. */
export type AwsClientCtor<C> = new (config: Record<string, unknown>) => C;

/**
 * A scoped AWS session. `client()` builds SDK clients bound to brokered
 * temporary credentials (or to the runner transport). There is deliberately
 * no accessor for the credentials themselves.
 */
export interface AwsSession {
  readonly provider: "aws";
  readonly accountId: string;
  readonly region: string;
  readonly expiresAt: string;
  readonly transport: "direct" | "runner" | "emulator";
  client<C>(ctor: AwsClientCtor<C>, overrides?: { region?: string }): C;
  /**
   * Environment for a child process that must authenticate (OpenTofu):
   * AWS_ACCESS_KEY_ID/SECRET/SESSION_TOKEN/REGION only. Callers pass it
   * straight to `spawn` and never persist or log it.
   */
  childProcessEnv(): Record<string, string>;
}

export interface GcpSession {
  readonly provider: "gcp";
  readonly projectId: string;
  readonly region: string;
  readonly expiresAt: string;
  /** bearer for Google REST APIs; never logged or persisted */
  authorizedFetch(url: string, init?: RequestInit): Promise<Response>;
  childProcessEnv(): Record<string, string>;
}

export interface AzureSession {
  readonly provider: "azure";
  readonly subscriptionId: string;
  readonly region: string;
  readonly expiresAt: string;
  authorizedFetch(url: string, init?: RequestInit): Promise<Response>;
  childProcessEnv(): Record<string, string>;
}

export interface KubernetesSession {
  readonly provider: "kubernetes";
  readonly server: string;
  readonly expiresAt: string;
  /** a configured `@kubernetes/client-node` KubeConfig, never serialized */
  kubeConfig(): unknown;
}

export type ProviderSession = AwsSession | GcpSession | AzureSession | KubernetesSession;

/* --------------------------------- broker --------------------------------- */

export type CredentialPurpose = "observe" | "deploy";

export interface CredentialRequest {
  connectionId: string;
  /** verified capability grant; the broker re-checks workspace + expiry */
  grant: CapabilityGrantClaims;
  purpose: CredentialPurpose;
  /** optional AWS inline session policy narrowing (JSON policy document) */
  sessionPolicy?: Record<string, unknown>;
  /** ≤ grant lifetime; default 900 */
  durationSec?: number;
}

export interface CredentialBroker {
  /**
   * Run `fn` with a scoped session. The session is invalid after `fn`
   * settles (clients built from it refuse further calls). Emits
   * `credential.assumed` / `credential.denied` events with no secret data.
   */
  withSession<T>(req: CredentialRequest, fn: (session: ProviderSession) => Promise<T>): Promise<T>;
  /**
   * Verify a connection can be assumed (read-only identity call). When
   * `opts.workspaceId` is given the connection must belong to that workspace,
   * otherwise it is reported as not found (no cross-tenant probing).
   */
  verifyConnection(
    connectionId: string,
    opts?: { workspaceId?: string }
  ): Promise<{ ok: boolean; detail: string; accountId?: string }>;
}

/**
 * Stable machine codes for why the broker refused. Messages are for humans and
 * never carry credential material; branch on `reason`, not on the message.
 */
export type DenialReason =
  | "grant_expired"
  | "grant_invalid"
  | "workspace_mismatch"
  | "connection_not_found"
  | "connection_revoked"
  | "connection_not_verified"
  | "provider_unsupported"
  | "mode_unsupported"
  | "not_supported"
  | "unknown_capability"
  | "purpose_capability_mismatch"
  | "role_arn_invalid"
  | "role_account_mismatch"
  | "external_id_missing"
  | "endpoint_not_permitted"
  | "duration_invalid"
  | "session_policy_invalid"
  | "session_policy_unavailable"
  | "sts_failed"
  | "issuer_unavailable"
  | "runner_unavailable"
  | "audit_failed";

export class CredentialDeniedError extends Error {
  readonly code = "credential_denied";
  readonly reason?: DenialReason;
  constructor(message?: string, options?: ErrorOptions & { reason?: DenialReason }) {
    super(message, options);
    this.name = "CredentialDeniedError";
    this.reason = options?.reason;
  }
}

/* ------------------------------ injected hooks ---------------------------- */

/**
 * Connection lookup, injected so this module does not depend on the control
 * store (the repository lands in another workstream). Implementations must not
 * throw for "missing" — return null. The broker (not the resolver) enforces
 * the workspace boundary against the grant.
 */
export type ConnectionResolver = (connectionId: string) => Promise<ProviderConnection | null>;

/**
 * An event the broker wants recorded. The event store assigns `seq`, `id` and
 * `ts`; the shape otherwise matches `PlatformEvent` for these two types.
 * `data` never contains keys, tokens or session policies — only identifiers.
 */
export interface CredentialEventDraft {
  type: "credential.assumed" | "credential.denied";
  /** always the GRANT's workspace, never the (possibly foreign) connection's */
  workspaceId: string;
  projectId?: string;
  environmentId?: string;
  resourceId?: string;
  operationId?: string;
  correlationId: string;
  data: Record<string, unknown>;
}

export type CredentialEventSink = (event: CredentialEventDraft) => void | Promise<void>;

/**
 * Transport hook for `runner` mode (ADR-0006): credentials never leave the
 * customer environment; SDK requests are relayed to the customer's
 * zenith-runner. The runner workstream provides the implementation.
 */
export interface RunnerAwsTransport {
  /** Build an SDK client whose requests are executed by the runner. */
  client<C>(ctor: AwsClientCtor<C>, overrides?: { region?: string }): C;
  close?(): void | Promise<void>;
}

export interface RunnerAwsTransportFactory {
  open(input: {
    connection: ProviderConnection;
    config: AwsConnectionConfig;
    grant: CapabilityGrantClaims;
    purpose: CredentialPurpose;
    roleArn: string;
    expiresAt: Date;
    /** compact inline session policy the runner should apply if it assumes a role itself */
    sessionPolicy?: string;
  }): Promise<RunnerAwsTransport> | RunnerAwsTransport;
}
