/** Independently compute OCI signatures with Node crypto using a synthetic key.
 * Oracle's published example does not provide a complete expected signature.
 * This fixture key is test material and cannot authenticate to any tenancy.
 */
import { createHash, generateKeyPairSync, sign } from "node:crypto";
import { writeFileSync } from "node:fs";

const { privateKey, publicKey } = generateKeyPairSync("rsa", {
  modulusLength: 2048,
  privateKeyEncoding: { type: "pkcs8", format: "pem" },
  publicKeyEncoding: { type: "spki", format: "pem" },
});
const keyId = "ST$synthetic-test-token";
const date = "Thu, 01 Oct 2026 00:00:00 GMT";
const host = "iaas.us-ashburn-1.oraclecloud.com";
const cases = [
  { method: "GET", uri: "/20160918/subnets?compartmentId=ocid1.compartment.oc1..fixture&displayName=a%20b&displayName=c%2Bd", body: "" },
  { method: "POST", uri: "/20220915/backups", body: '{"displayName":"café","dbSystemId":"ocid1.dbsystem.oc1.iad.fixture"}' },
  { method: "PUT", uri: "/synthetic/test", body: "" },
  { method: "DELETE", uri: "/synthetic/test", body: "" },
].map(({ method, uri, body }) => {
  const bytes = Buffer.from(body, "utf8");
  const lines = [`(request-target): ${method.toLowerCase()} ${uri}`, `host: ${host}`, `date: ${date}`];
  const signedHeaders = ["(request-target)", "host", "date"];
  if (method === "POST" || method === "PUT") {
    signedHeaders.push("x-content-sha256", "content-type", "content-length");
    lines.push(`x-content-sha256: ${createHash("sha256").update(bytes).digest("base64")}`, "content-type: application/json", `content-length: ${bytes.length}`);
  }
  const canonical = lines.join("\n");
  return { method, uri, bodyB64: bytes.toString("base64"), canonical, signedHeaders: signedHeaders.join(" "), signature: sign("RSA-SHA256", Buffer.from(canonical), privateKey).toString("base64") };
});
writeFileSync(new URL("../go/internal/oci/testdata/signing-vector.json", import.meta.url), `${JSON.stringify({ note: "Synthetic test key; independently generated by Node crypto, never an OCI credential", privateKey, publicKey, keyId, date, host, cases }, null, 2)}\n`);
