/** Metadata writer for reproducible procedural raster exports. */
export const GIMBAL_PROVENANCE = 'Origin: original procedural Gimbal geometry and deterministic CPU projection render generated by scripts/gimbal-build.mjs in the Zenith repository. No AI image model was used. Palette, rig pivots, views and poses are reproducible from that script.';

function textChunk(value) {
  const data = Buffer.from(`prompt\0${value}`, 'latin1');
  const body = Buffer.concat([Buffer.from('tEXt'), data]);
  let crc = 0xffffffff;
  for (const byte of body) {
    crc ^= byte;
    for (let bit = 0; bit < 8; bit++) crc = (crc >>> 1) ^ (0xedb88320 & -(crc & 1));
  }
  const chunk = Buffer.alloc(data.length + 12);
  chunk.writeUInt32BE(data.length, 0);
  body.copy(chunk, 4);
  chunk.writeUInt32BE((crc ^ 0xffffffff) >>> 0, chunk.length - 4);
  return chunk;
}

/** Preserve image data and other metadata; replace only an existing prompt key. */
export function withGimbalProvenance(png) {
  const signature = Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]);
  if (!png.subarray(0, 8).equals(signature)) throw new Error('Expected a PNG raster.');
  const chunks = [png.subarray(0, 8)];
  for (let offset = 8; offset < png.length;) {
    const size = png.readUInt32BE(offset), end = offset + size + 12;
    if (end > png.length) throw new Error('PNG chunk exceeds buffer.');
    const type = png.toString('ascii', offset + 4, offset + 8);
    const data = png.subarray(offset + 8, offset + 8 + size);
    const isPrompt = type === 'tEXt' && data.subarray(0, data.indexOf(0)).toString('latin1') === 'prompt';
    if (!isPrompt) chunks.push(png.subarray(offset, end));
    if (type === 'IHDR') chunks.push(textChunk(GIMBAL_PROVENANCE));
    offset = end;
  }
  return Buffer.concat(chunks);
}
