"use client";
/**
 * Application logs for one service, or all of them at once. Every line here is
 * generated by Orrery's sandbox simulator — the card says so twice, and the
 * chip only reads "live" if the stream itself claims to be.
 */
import { useCallback, useEffect, useMemo, useState } from "react";
import { useEventStream } from "@/lib/client/api";
import type { Manifest, Revision } from "@/lib/domain/types";
import { Callout } from "@/components/ui/callout";
import { Card } from "@/components/ui/card";
import { Chip } from "@/components/ui/chip";
import { LogViewer, type LogLine } from "@/components/ui/log-viewer";
import { Select } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Sparkline } from "@/components/ui/sparkline";
import { ErrorNote } from "@/components/screens/shared";

const LOG_EVENTS = ["log", "error"];
const ALL_SERVICES = "__all__";

interface WireLine {
  seq: number;
  ts: string;
  line: string;
  stream?: string;
  /** SEAM (B12): the server does not send this yet; when it does, it wins. */
  simulated?: boolean;
}

export interface LogsPanelProps {
  environmentId: string;
  working: Manifest;
  running: Revision | undefined;
  runningLoading: boolean;
  deployed: boolean;
  providerName: string;
  providerIsSandbox: boolean;
}

export function LogsPanel({
  environmentId,
  working,
  running,
  runningLoading,
  deployed,
  providerName,
  providerIsSandbox,
}: LogsPanelProps) {
  const liveServices = useMemo(() => running?.manifest.services ?? [], [running]);
  const undeployed = useMemo(
    () => working.services.filter((s) => !liveServices.some((d) => d.id === s.id)),
    [working, liveServices]
  );

  // Deep link from the inspector: /observe?service=<id>. Read once, the same
  // way the System Map reads ?select=, so this page needs no Suspense boundary.
  const [serviceId, setServiceId] = useState(() => {
    if (typeof window === "undefined") return "";
    return new URLSearchParams(window.location.search).get("service") ?? "";
  });
  useEffect(() => {
    // Default to something that is actually running, not services[0] of the
    // working copy — an undeployed service streams nothing, forever. A deep
    // link that names a real service (live or undeployed) is kept.
    setServiceId((current) =>
      current && [...liveServices, ...undeployed].some((s) => s.id === current)
        ? current
        : (liveServices[0]?.id ?? "")
    );
  }, [liveServices, undeployed]);

  const allMode = serviceId === ALL_SERVICES;
  const chosenIsUndeployed = undeployed.some((s) => s.id === serviceId);
  const serviceName = liveServices.find((s) => s.id === serviceId)?.name ?? "service";

  const [lines, setLines] = useState<LogLine[]>([]);
  const [streamError, setStreamError] = useState<string>();
  /** undefined = the stream says nothing about it; see WireLine.simulated. */
  const [wireSimulated, setWireSimulated] = useState<boolean>();

  useEffect(() => {
    setLines([]);
    setStreamError(undefined);
    setWireSimulated(undefined);
  }, [serviceId, environmentId]);

  const addLines = useCallback((incoming: LogLine[], simulated?: boolean) => {
    if (typeof simulated === "boolean") setWireSimulated(simulated);
    setLines((prev) => [...prev, ...incoming]);
  }, []);

  const onEvent = useCallback(
    (type: string, raw: unknown) => {
      if (type === "error") {
        const e = raw as { message?: string; fix?: string };
        setStreamError([e.message, e.fix].filter(Boolean).join(" "));
        return;
      }
      const l = raw as WireLine;
      // The generator says which handle a line came out of; keep that, so stderr
      // stays visibly stderr and the viewer's stream filter has something to do.
      addLines(
        [
          {
            seq: l.seq,
            ts: l.ts,
            line: l.line,
            stream: l.stream === "stderr" ? "stderr" : "stdout",
          },
        ],
        l.simulated
      );
    },
    [addLines]
  );

  const { connected } = useEventStream(
    deployed && serviceId && !allMode && !chosenIsUndeployed
      ? `/api/logs/${environmentId}/${serviceId}`
      : null,
    LOG_EVENTS,
    onEvent
  );

  /** In all-services mode every service gets its own stream; see LogFeed. */
  const merged = useMemo(
    () => (allMode ? [...lines].sort((a, b) => (a.ts ?? "").localeCompare(b.ts ?? "")) : lines),
    [allMode, lines]
  );

  const perMinute = useMemo(() => ratePerMinute(merged), [merged]);
  const errors = merged.filter((l) => l.stream === "stderr").length;

  const options = [
    ...(liveServices.length > 1
      ? [{ value: ALL_SERVICES, label: `All ${liveServices.length} deployed services` }]
      : []),
    ...liveServices.map((s) => ({ value: s.id, label: `${s.name} (${s.kind})` })),
    ...undeployed.map((s) => ({
      value: s.id,
      label: `${s.name} (${s.kind}) — not deployed here`,
    })),
  ];

  return (
    <Card
      title="Application logs"
      subtitle={
        providerIsSandbox
          ? `Generated by Orrery's sandbox from r${running?.number ?? "?"} — not read from a running process.`
          : `Generated by Orrery's sandbox simulator. ${providerName} does not stream logs to Orrery; these lines were never produced by it.`
      }
      actions={
        <>
          <Chip
            tone={wireSimulated === false ? "ok" : "info"}
            title={
              wireSimulated === undefined
                ? "The log stream does not label itself yet; everything Orrery generates here is simulated."
                : "The stream labels its own frames."
            }
          >
            {wireSimulated === false ? "live" : "simulated"}
          </Chip>
          {deployed && !allMode && !chosenIsUndeployed && (
            <Chip tone={connected ? "signal" : "warn"}>
              {connected ? "streaming" : "reconnecting"}
            </Chip>
          )}
        </>
      }
    >
      {working.services.length === 0 ? (
        <p className="text-[13px] text-ink-mute">This system has no services yet.</p>
      ) : !deployed ? (
        <p className="text-[13px] text-ink-mute">
          Nothing is running in this environment yet — deploy it and logs start here.
        </p>
      ) : runningLoading && !running ? (
        <Skeleton height={380} />
      ) : liveServices.length === 0 ? (
        <p className="text-[13px] text-ink-mute">
          r{running?.number ?? "?"} has no services in it, so nothing is running to log
          {undeployed.length > 0
            ? ` — the ${undeployed.length} service${undeployed.length === 1 ? "" : "s"} in the working copy start logging once you deploy.`
            : "."}
        </p>
      ) : (
        <div className="space-y-3">
          <Select
            value={serviceId}
            onChange={(e) => setServiceId(e.target.value)}
            aria-label="Service"
            options={options}
          />

          {allMode &&
            liveServices.map((s) => (
              <LogFeed
                key={s.id}
                url={`/api/logs/${environmentId}/${s.id}`}
                name={s.name}
                onLines={addLines}
              />
            ))}

          {chosenIsUndeployed ? (
            <Callout tone="warn">
              {working.services.find((s) => s.id === serviceId)?.name} is in the working copy but
              not in r{running?.number ?? "?"}, so nothing is running to log. Deploy this
              environment to see its output.
            </Callout>
          ) : (
            <>
              {streamError && <ErrorNote error={new Error(streamError)} />}
              <div className="flex flex-wrap items-center gap-3 rounded-card border border-line bg-bg1 px-3 py-2">
                <Sparkline
                  points={perMinute.points}
                  label={`Lines per minute over the last ${perMinute.points.length} minutes of the sample`}
                />
                <span className="tnum text-[12.5px] text-ink">
                  {perMinute.current}/min
                  <span className="text-ink-faint"> in this sample</span>
                </span>
                <span className="tnum text-[12.5px] text-ink-faint">
                  {errors} on stderr of {merged.length}
                </span>
                <Chip tone="info" className="ml-auto">
                  synthetic
                </Chip>
              </div>
              <LogViewer
                lines={merged}
                height={380}
                label={allMode ? "all services, application logs" : `${serviceName} application logs`}
                downloadName={`${allMode ? "all-services" : serviceName}-logs.txt`}
                emptyMessage="Waiting for the next line — the sandbox emits one every couple of seconds."
              />
              <p className="text-[11.5px] leading-relaxed text-ink-faint">
                On connect the sandbox replays its last 200 lines per service (about seven minutes)
                and streams from there; anything older than that was never stored. Search, level and
                stream filters — and Download — work on the {merged.length} line
                {merged.length === 1 ? "" : "s"} loaded here, not on the server.
              </p>
            </>
          )}
        </div>
      )}
    </Card>
  );
}

/**
 * One service's stream, rendered as nothing. All-services mode needs one
 * EventSource per service and hooks cannot be called in a loop — a component
 * per feed is the honest way to say "N streams".
 */
function LogFeed({
  url,
  name,
  onLines,
}: {
  url: string;
  name: string;
  onLines: (lines: LogLine[], simulated?: boolean) => void;
}) {
  const onEvent = useCallback(
    (type: string, raw: unknown) => {
      if (type !== "log") return;
      const l = raw as WireLine;
      onLines(
        [
          {
            // no seq: sequence numbers are per service and would collide here
            ts: l.ts,
            line: `[${name}] ${l.line}`,
            stream: l.stream === "stderr" ? "stderr" : "stdout",
          },
        ],
        l.simulated
      );
    },
    [name, onLines]
  );
  useEventStream(url, LOG_EVENTS, onEvent);
  return null;
}

/** Lines per minute over the sample that is loaded, oldest bucket first. */
function ratePerMinute(lines: LogLine[]): { points: number[]; current: number } {
  const counts = new Map<number, number>();
  for (const l of lines) {
    const t = l.ts ? Date.parse(l.ts) : NaN;
    if (Number.isNaN(t)) continue;
    const minute = Math.floor(t / 60000);
    counts.set(minute, (counts.get(minute) ?? 0) + 1);
  }
  if (counts.size === 0) return { points: [], current: 0 };
  const minutes = [...counts.keys()].sort((a, b) => a - b);
  const points: number[] = [];
  for (let m = minutes[0]; m <= minutes[minutes.length - 1]; m++) points.push(counts.get(m) ?? 0);
  // The newest minute is still filling up, so the rate is the one before it.
  return { points, current: points.length > 1 ? points[points.length - 2] : points[0] };
}
