/**
 * Closed provider configuration vocabulary. Credentials come from sessions;
 * config cannot select another identity, endpoint, proxy or trust store.
 * Nested blocks are closed too: Azure currently needs only empty features.
 */
import type { ProviderLocalName } from "@/lib/tofu/providers";
import { TofuWorkspaceError } from "@/lib/tofu/workspace-error";

type Check = (value: unknown) => boolean;
const text: Check = (v) => typeof v === "string" && v.length > 0 && v.length <= 256 && /^[A-Za-z0-9_-]+$/.test(v);
const region: Check = (v) => typeof v === "string" && /^[a-z0-9-]{3,40}$/.test(v);
const empty: Check = (v) => object(v) && Object.keys(v).length === 0;
const enabled: Check = (v) => v === true;
const tags: Check = (v) => object(v) && Object.values(v).every((s) => typeof s === "string");
const defaultTags: Check = (v) => object(v) && Object.keys(v).every((k) => k === "tags") && tags(v.tags);

function object(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

const ALLOWED: Record<ProviderLocalName, Readonly<Record<string, Check>>> = {
  // Region/default_tags are normally generated by the assembler, but they
  // must also validate after a serialized workspace crosses a queue.
  aws: { region, default_tags: defaultTags },
  google: { project: text, region },
  azurerm: {
    subscription_id: text,
    features: empty,
    storage_use_azuread: enabled,
    resource_provider_registrations: (v) => v === "none",
  },
  oci: { region, auth: (v) => typeof v === "string" && ["InstancePrincipal", "ResourcePrincipal", "OKEWorkloadIdentity"].includes(v) },
  kubernetes: {},
  random: {},
};

/** Refuse unknown keys and malformed values without echoing external text. */
export function assertProviderConfig(value: unknown): void {
  if (value === undefined) return;
  if (!object(value)) throw new TofuWorkspaceError("forbidden_construct", "Provider configuration must be an object.");
  for (const [name, config] of Object.entries(value)) {
    if (!Object.hasOwn(ALLOWED, name) || !object(config)) {
      throw new TofuWorkspaceError("forbidden_construct", "Provider configuration is outside the allowlist.");
    }
    const keys = ALLOWED[name as ProviderLocalName];
    for (const [key, v] of Object.entries(config)) {
      if (!Object.hasOwn(keys, key) || !keys[key](v)) {
        throw new TofuWorkspaceError("forbidden_construct", "Provider argument is outside the non-secret, non-routing allowlist.");
      }
    }
  }
}
